/*
 * Generated by firmware/tools/gen_contract.py from glucocube/contract.py.
 * Do not edit by hand — edit the Python and regenerate, or CI will fail.
 */

#include "gc_contract.h"

#include <string.h>

const uint32_t gc_palette[GC_THEME_COUNT][GC_C_COUNT] = {
    [GC_THEME_DARK] = {
        [GC_C_BG] = 0x0A0C0F,
        [GC_C_BAND] = 0x14191E,
        [GC_C_LINE] = 0x262D34,
        [GC_C_FG] = 0xE9EDF1,
        [GC_C_DIM] = 0x7A848E,
        [GC_C_FAINT] = 0x545D66,
        [GC_C_TRACE] = 0x9DA5AE,
        [GC_C_STALE] = 0x606870,
        [GC_C_IN_RANGE] = 0x5FDE96,
        [GC_C_HIGH] = 0xE9B949,
        [GC_C_LOW] = 0xF45C54,
        [GC_C_URGENT] = 0xFF453A,
    },
    [GC_THEME_LIGHT] = {
        [GC_C_BG] = 0xF6F7F5,
        [GC_C_BAND] = 0xE9EBE6,
        [GC_C_LINE] = 0xD1D4CF,
        [GC_C_FG] = 0x181C20,
        [GC_C_DIM] = 0x666E76,
        [GC_C_FAINT] = 0x949BA2,
        [GC_C_TRACE] = 0x7A828A,
        [GC_C_STALE] = 0xAAB0B6,
        [GC_C_IN_RANGE] = 0x109448,
        [GC_C_HIGH] = 0xB07408,
        [GC_C_LOW] = 0xCC2C24,
        [GC_C_URGENT] = 0xE00000,
    },
};

static const char *const theme_names[GC_THEME_COUNT] = {
    [GC_THEME_DARK] = "dark",
    [GC_THEME_LIGHT] = "light",
};

uint16_t gc_rgb_to_565(uint32_t rgb)
{
    uint32_t r = (rgb >> 16) & 0xFF, g = (rgb >> 8) & 0xFF, b = rgb & 0xFF;
    return (uint16_t)(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3));
}

uint32_t gc_color888(gc_theme_t theme, gc_color_t role)
{
    if (theme >= GC_THEME_COUNT || role >= GC_C_COUNT) {
        return 0;
    }
    return gc_palette[theme][role];
}

uint16_t gc_color565(gc_theme_t theme, gc_color_t role)
{
    return gc_rgb_to_565(gc_color888(theme, role));
}

const char *gc_theme_name(gc_theme_t theme)
{
    return theme < GC_THEME_COUNT ? theme_names[theme] : theme_names[GC_DEFAULT_THEME];
}

gc_theme_t gc_theme_from_name(const char *name)
{
    for (int i = 0; name && i < GC_THEME_COUNT; i++) {
        if (strcmp(name, theme_names[i]) == 0) {
            return (gc_theme_t)i;
        }
    }
    return GC_DEFAULT_THEME;
}

const int gc_horizons[GC_HORIZON_COUNT] = {30, 60, 90, 120};

const gc_direction_t gc_directions[GC_DIRECTION_COUNT] = {
    {"DoubleUp", -90, 2},
    {"SingleUp", -90, 1},
    {"FortyFiveUp", -45, 1},
    {"Flat", 0, 1},
    {"FortyFiveDown", 45, 1},
    {"SingleDown", 90, 1},
    {"DoubleDown", 90, 2},
};

const gc_direction_t *gc_direction_lookup(const char *name)
{
    for (int i = 0; name && i < GC_DIRECTION_COUNT; i++) {
        if (strcmp(name, gc_directions[i].direction) == 0) {
            return &gc_directions[i];
        }
    }
    return NULL;
}

const gc_tick_t gc_ticks[GC_TICK_COUNT] = {
    {-180, "-3H"},
    {-120, "-2H"},
    {-60, "-1H"},
    {0, "NOW"},
    {60, "+1H"},
    {120, "+2H"},
};

static const struct { const char *type; const char *label; } source_labels[] = {
    {"tidepool", "TWIIST"},
    {"nightscout", "NS"},
    {"glucocore", "GLUCOCORE"},
};

const char *gc_source_label(const char *source_type)
{
    size_t n = sizeof(source_labels) / sizeof(source_labels[0]);
    for (size_t i = 0; source_type && i < n; i++) {
        if (strcmp(source_type, source_labels[i].type) == 0) {
            return source_labels[i].label;
        }
    }
    return "TRIO";
}

const char *const gc_captive_probe_paths[GC_CAPTIVE_PROBE_COUNT] = {
    "/generate_204",
    "/gen_204",
    "/mobile/status.php",
    "/hotspot-detect.html",
    "/hotspotdetect.html",
    "/library/test/success.html",
    "/success.txt",
    "/canonical.html",
    "/ncsi.txt",
    "/connecttest.txt",
    "/redirect",
    "/nmcheck.gnome.org",
};

const char *const gc_captive_always_serve[GC_CAPTIVE_ALWAYS_SERVE_COUNT] = {
    "/setup",
    "/screen.png",
    "/fonts/",
    "/api/",
};

const char *const gc_qr_glyph[GC_QR_GLYPH_ROWS] = {
    "XXX.XXX",
    "X.X.X.X",
    "XXX.XXX",
    "..X.X..",
    "XXX..XX",
    "X.X.X.X",
    "XXX..X.",
};

static const char *const channel_names[GC_CHANNEL_COUNT] = {
    [GC_CHANNEL_STABLE] = "stable",
    [GC_CHANNEL_BETA] = "beta",
};

static const char *const channel_labels[GC_CHANNEL_COUNT] = {
    [GC_CHANNEL_STABLE] = "Standard",
    [GC_CHANNEL_BETA] = "Beta",
};

const char *gc_channel_name(gc_channel_t channel)
{
    return channel < GC_CHANNEL_COUNT ? channel_names[channel]
                                      : channel_names[GC_CHANNEL_STABLE];
}

const char *gc_channel_label(gc_channel_t channel)
{
    return channel < GC_CHANNEL_COUNT ? channel_labels[channel]
                                      : channel_labels[GC_CHANNEL_STABLE];
}

gc_channel_t gc_channel_from_name(const char *name)
{
    for (int i = 0; name && i < GC_CHANNEL_COUNT; i++) {
        if (strcmp(name, channel_names[i]) == 0) {
            return (gc_channel_t)i;
        }
    }
    return GC_CHANNEL_STABLE;
}
