/*
 * Generated by firmware/host_test/gen_vectors.py — do not edit by hand.
 * Expected values come from running glucocube/oref.py and predict.py.
 */

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "gc_oref.h"
#include "gc_predict.h"
#include "gc_store.h"
#include "gc_version.h"

#define GC_VECTOR_NOW 1700000000000LL
#define GC_VECTOR_STEPS 24

typedef struct {
    const char *name;
    float sgv;
    const gc_point_t *history;
    int history_count;
    const gc_point_t *boluses;
    int bolus_count;
    bool has_pump_iob;
    float pump_iob;
    bool has_cob;
    float cob;
    gc_params_t params;
    int steps;
    const float *expected;
    int expected_count;
    gc_curve_t expected_curve;
} gc_oref_vector_t;

typedef struct {
    const char *candidate;
    const char *current;
    bool expect_newer;
} gc_version_vector_t;

typedef struct {
    const char *version;
    bool expect_prerelease;
} gc_prerelease_vector_t;

typedef struct {
    const char *name;
    gc_snapshot_t snapshot;
    bool expect_valid;
    bool expect_estimated;
    bool horizon_valid[GC_HORIZON_COUNT];
    float horizons[GC_HORIZON_COUNT];
    int series_count;
    const gc_point_t *series;
} gc_predict_vector_t;

extern const gc_oref_vector_t gc_oref_vectors[];
extern const int gc_oref_vector_count;
extern const gc_predict_vector_t gc_predict_vectors[];
extern const int gc_predict_vector_count;
extern const gc_version_vector_t gc_version_vectors[];
extern const int gc_version_vector_count;
extern const gc_prerelease_vector_t gc_prerelease_vectors[];
extern const int gc_prerelease_vector_count;

/* The snapshot in a predict vector carries counts but not the arrays
 * themselves — they are too long to sit in a designated initialiser. The
 * runner copies them in from these. */
const gc_point_t *gc_predict_history(int index);
const gc_point_t *gc_predict_boluses(int index);
const float *gc_predict_device_values(int index);
