/*
 * Generated by firmware/host_test/gen_vectors.py — do not edit by hand.
 */

#include "vectors.h"

static const gc_point_t oref_hist_0[12] = {
    {1699996700000LL, 120.0f},
    {1699997000000LL, 120.0f},
    {1699997300000LL, 120.0f},
    {1699997600000LL, 120.0f},
    {1699997900000LL, 120.0f},
    {1699998200000LL, 120.0f},
    {1699998500000LL, 120.0f},
    {1699998800000LL, 120.0f},
    {1699999100000LL, 120.0f},
    {1699999400000LL, 120.0f},
    {1699999700000LL, 120.0f},
    {1700000000000LL, 120.0f},
};
static const gc_point_t oref_bolus_0[1] = {{0, 0.0f}};
static const float oref_expect_0[24] = {
    120.0f, 120.0f, 120.0f, 120.0f, 120.0f, 120.0f,
    120.0f, 120.0f, 120.0f, 120.0f, 120.0f, 120.0f,
    120.0f, 120.0f, 120.0f, 120.0f, 120.0f, 120.0f,
    120.0f, 120.0f, 120.0f, 120.0f, 120.0f, 120.0f,
};

static const gc_point_t oref_hist_1[12] = {
    {1699996700000LL, 142.0f},
    {1699997000000LL, 142.0f},
    {1699997300000LL, 142.0f},
    {1699997600000LL, 142.0f},
    {1699997900000LL, 142.0f},
    {1699998200000LL, 142.0f},
    {1699998500000LL, 142.0f},
    {1699998800000LL, 142.0f},
    {1699999100000LL, 142.0f},
    {1699999400000LL, 142.0f},
    {1699999700000LL, 142.0f},
    {1700000000000LL, 142.0f},
};
static const gc_point_t oref_bolus_1[2] = {
    {1699994600000LL, 2.5f},
    {1699998500000LL, 1.2f},
};
static const float oref_expect_1[24] = {
    141.25430244783402f, 140.155001455962f, 138.72906555736574f, 137.00050409263304f, 134.99061416135893f, 132.71820948881575f,
    130.1998324321964f, 127.44995027213783f, 124.48113686148857f, 121.30424063410521f, 117.92853991157433f, 114.36188638489837f,
    110.61083759111573f, 106.96805564082761f, 103.43786695488605f, 100.02364261658575f, 96.72789400652422f, 93.55236079355223f,
    90.49809182703368f, 87.565519439387f, 84.75452763392857f, 82.0645146012438f, 79.49444997753977f, 77.04292723056113f,
};

static const gc_point_t oref_hist_2[10] = {
    {1699997300000LL, 160.0f},
    {1699997600000LL, 161.5f},
    {1699997900000LL, 163.0f},
    {1699998200000LL, 164.5f},
    {1699998500000LL, 166.0f},
    {1699998800000LL, 167.5f},
    {1699999100000LL, 169.0f},
    {1699999400000LL, 170.5f},
    {1699999700000LL, 172.0f},
    {1700000000000LL, 173.5f},
};
static const gc_point_t oref_bolus_2[1] = {{0, 0.0f}};
static const float oref_expect_2[24] = {
    175.31361212006414f, 175.05719777213756f, 174.26412899445234f, 172.9640494877233f, 171.18318768353583f, 168.94464681667174f,
    166.26867356090375f, 163.17290668755973f, 159.67260711211873f, 155.78087060589183f, 151.50882436710242f, 146.86580856808922f,
    141.85954392259742f, 137.00315478279236f, 132.30157454226756f, 127.7585454002131f, 123.37673914690848f, 119.15786824748602f,
    115.10278791771654f, 111.21158983937683f, 107.48368811949594f, 103.91789805726377f, 100.51250824445371f, 97.26534648970198f,
};

static const gc_point_t oref_hist_3[10] = {
    {1699997300000LL, 100.0f},
    {1699997600000LL, 98.8f},
    {1699997900000LL, 97.6f},
    {1699998200000LL, 96.4f},
    {1699998500000LL, 95.2f},
    {1699998800000LL, 94.0f},
    {1699999100000LL, 92.8f},
    {1699999400000LL, 91.6f},
    {1699999700000LL, 90.4f},
    {1700000000000LL, 89.2f},
};
static const gc_point_t oref_bolus_3[1] = {{0, 0.0f}};
static const float oref_expect_3[24] = {
    87.09659696998396f, 86.40445055696561f, 85.91521775138693f, 85.6214876280692f, 85.51670307911607f, 85.5950882958321f,
    85.85158160977409f, 86.28177332811009f, 86.88184822197033f, 87.64853234852706f, 88.5790439082244f, 89.67104785797771f,
    90.92261401935066f, 92.13671130430193f, 93.31210636443313f, 94.44786364994675f, 95.5433152132729f, 96.59803293812851f,
    97.61180302057089f, 98.58460254015581f, 99.51657797012604f, 100.40802548568408f, 101.2593729388866f, 102.07116337757454f,
};

static const gc_point_t oref_hist_4[12] = {
    {1699996700000LL, 120.0f},
    {1699997000000LL, 121.2f},
    {1699997300000LL, 122.4f},
    {1699997600000LL, 123.6f},
    {1699997900000LL, 124.8f},
    {1699998200000LL, 126.0f},
    {1699998500000LL, 127.2f},
    {1699998800000LL, 128.4f},
    {1699999100000LL, 129.6f},
    {1699999400000LL, 130.8f},
    {1699999700000LL, 132.0f},
    {1700000000000LL, 133.2f},
};
static const gc_point_t oref_bolus_4[1] = {
    {1699998800000LL, 4.0f},
};
static const float oref_expect_4[24] = {
    138.6563870364802f, 142.11217473367935f, 144.44192967897737f, 145.71323782618f, 145.98724825237105f, 145.31917862623894f,
    143.7587849145593f, 141.35079769420864f, 138.13532728748604f, 134.14823979805556f, 129.42150599294632f, 123.98352485225185f,
    118.39275682530379f, 112.84911283415143f, 107.37198940728376f, 101.97828467495223f, 96.68261875625294f, 91.49753753917571f,
    86.43370099778666f, 81.50005711637658f, 76.70400242070546f, 72.05153005112295f, 67.54736625108308f, 63.19509608715117f,
};

static const gc_point_t oref_hist_5[12] = {
    {1699996700000LL, 101.0f},
    {1699997000000LL, 101.0f},
    {1699997300000LL, 101.0f},
    {1699997600000LL, 101.0f},
    {1699997900000LL, 101.0f},
    {1699998200000LL, 101.0f},
    {1699998500000LL, 101.0f},
    {1699998800000LL, 101.0f},
    {1699999100000LL, 101.0f},
    {1699999400000LL, 101.0f},
    {1699999700000LL, 101.0f},
    {1700000000000LL, 101.0f},
};
static const gc_point_t oref_bolus_5[1] = {{0, 0.0f}};
static const float oref_expect_5[24] = {
    109.0f, 109.0f, 109.0f, 109.0f, 109.0f, 109.0f,
    109.0f, 109.0f, 109.0f, 109.0f, 109.0f, 109.0f,
    109.0f, 109.0f, 109.0f, 109.0f, 109.0f, 109.0f,
    109.0f, 109.0f, 109.0f, 109.0f, 109.0f, 109.0f,
};

static const gc_point_t oref_hist_6[10] = {
    {1699997300000LL, 150.0f},
    {1699997600000LL, 155.2f},
    {1699997900000LL, 160.4f},
    {1699998200000LL, 165.6f},
    {1699998500000LL, 170.8f},
    {1699998800000LL, 176.0f},
    {1699999100000LL, 181.2f},
    {1699999400000LL, 186.4f},
    {1699999700000LL, 191.6f},
    {1700000000000LL, 196.8f},
};
static const gc_point_t oref_bolus_6[1] = {{0, 0.0f}};
static const float oref_expect_6[24] = {
    201.2f, 205.96666666666667f, 210.3f, 214.20000000000002f, 217.66666666666669f, 220.70000000000002f,
    223.3f, 225.46666666666667f, 227.2f, 228.5f, 229.36666666666667f, 229.8f,
    229.8f, 229.8f, 229.8f, 229.8f, 229.8f, 229.8f,
    229.8f, 229.8f, 229.8f, 229.8f, 229.8f, 229.8f,
};

static const gc_point_t oref_hist_7[10] = {
    {1699997300000LL, 130.0f},
    {1699997600000LL, 122.5f},
    {1699997900000LL, 115.0f},
    {1699998200000LL, 107.5f},
    {1699998500000LL, 100.0f},
    {1699998800000LL, 92.5f},
    {1699999100000LL, 85.0f},
    {1699999400000LL, 77.5f},
    {1699999700000LL, 70.0f},
    {1700000000000LL, 62.5f},
};
static const gc_point_t oref_bolus_7[1] = {
    {1699998200000LL, 6.0f},
};
static const float oref_expect_7[24] = {
    50.505207149857426f, 39.0f, 39.0f, 39.0f, 39.0f, 39.0f,
    39.0f, 39.0f, 39.0f, 39.0f, 39.0f, 39.0f,
    39.0f, 39.0f, 39.0f, 39.0f, 39.0f, 39.0f,
    39.0f, 39.0f, 39.0f, 39.0f, 39.0f, 39.0f,
};

static const gc_point_t oref_hist_8[10] = {
    {1699997300000LL, 300.0f},
    {1699997600000LL, 305.5f},
    {1699997900000LL, 311.0f},
    {1699998200000LL, 316.5f},
    {1699998500000LL, 322.0f},
    {1699998800000LL, 327.5f},
    {1699999100000LL, 333.0f},
    {1699999400000LL, 338.5f},
    {1699999700000LL, 344.0f},
    {1700000000000LL, 349.5f},
};
static const gc_point_t oref_bolus_8[1] = {{0, 0.0f}};
static const float oref_expect_8[24] = {
    360.0f, 367.73333333333335f, 375.2f, 382.4f, 389.3333333333333f, 396.0f,
    401.0f, 401.0f, 401.0f, 401.0f, 401.0f, 401.0f,
    401.0f, 401.0f, 401.0f, 401.0f, 401.0f, 401.0f,
    401.0f, 401.0f, 401.0f, 401.0f, 401.0f, 401.0f,
};

static const gc_point_t oref_hist_9[12] = {
    {1699996700000LL, 150.0f},
    {1699997000000LL, 150.0f},
    {1699997300000LL, 150.0f},
    {1699997600000LL, 150.0f},
    {1699997900000LL, 150.0f},
    {1699998200000LL, 150.0f},
    {1699998500000LL, 150.0f},
    {1699998800000LL, 150.0f},
    {1699999100000LL, 150.0f},
    {1699999400000LL, 150.0f},
    {1699999700000LL, 150.0f},
    {1700000000000LL, 150.0f},
};
static const gc_point_t oref_bolus_9[1] = {
    {1699997300000LL, 3.0f},
};
static const float oref_expect_9[24] = {
    146.97685699937173f, 143.8465587464101f, 140.63555542365378f, 137.36756515460084f, 134.06379636210445f, 130.74315407004028f,
    127.42243122542216f, 124.11648604943201f, 120.83840636134282f, 117.59966175879842f, 114.41024448113316f, 111.27879972914327f,
    108.21274616475115f, 105.21838726713358f, 102.30101417792947f, 99.4650006269265f, 96.71389049098244f, 94.05047850271222f,
    91.47688459151735f, 88.99462230771418f, 86.60466175070115f, 84.30748739417008f, 82.10315117519976f, 79.99132118956165f,
};

static const gc_point_t oref_hist_10[12] = {
    {1699996700000LL, 150.0f},
    {1699997000000LL, 150.0f},
    {1699997300000LL, 150.0f},
    {1699997600000LL, 150.0f},
    {1699997900000LL, 150.0f},
    {1699998200000LL, 150.0f},
    {1699998500000LL, 150.0f},
    {1699998800000LL, 150.0f},
    {1699999100000LL, 150.0f},
    {1699999400000LL, 150.0f},
    {1699999700000LL, 150.0f},
    {1700000000000LL, 150.0f},
};
static const gc_point_t oref_bolus_10[1] = {
    {1699997300000LL, 3.0f},
};
static const float oref_expect_10[24] = {
    148.8710949405094f, 147.52688036028613f, 145.99919072837872f, 144.31485459459162f, 142.49628444493752f, 140.56200564661825f,
    138.52713030065513f, 136.40378129281552f, 134.20147135206184f, 131.92744148647208f, 129.5869627658653f, 127.18360505492724f,
    124.71947596745505f, 122.37869979544405f, 120.1610719561723f, 118.06549211613168f, 116.09011105340564f, 114.23246004503298f,
    112.48956458899771f, 110.85804409752876f, 109.3341990411139f, 107.91408687966047f, 106.59358798732035f, 105.36846265949254f,
};

static const gc_point_t oref_hist_11[4] = {
    {1699997600000LL, 120.0f},
    {1699998500000LL, 132.0f},
    {1699998800000LL, 138.0f},
    {1699999700000LL, 145.0f},
};
static const gc_point_t oref_bolus_11[1] = {{0, 0.0f}};
static const float oref_expect_11[24] = {
    151.0f, 156.5f, 161.5f, 166.0f, 170.0f, 173.5f,
    176.5f, 179.0f, 181.0f, 182.5f, 183.5f, 184.0f,
    184.0f, 184.0f, 184.0f, 184.0f, 184.0f, 184.0f,
    184.0f, 184.0f, 184.0f, 184.0f, 184.0f, 184.0f,
};

static const gc_point_t oref_hist_12[20] = {
    {1699998860000LL, 150.0f},
    {1699998920000LL, 150.5f},
    {1699998980000LL, 151.0f},
    {1699999040000LL, 151.5f},
    {1699999100000LL, 152.0f},
    {1699999160000LL, 152.5f},
    {1699999220000LL, 153.0f},
    {1699999280000LL, 153.5f},
    {1699999340000LL, 154.0f},
    {1699999400000LL, 154.5f},
    {1699999460000LL, 155.0f},
    {1699999520000LL, 155.5f},
    {1699999580000LL, 156.0f},
    {1699999640000LL, 156.5f},
    {1699999700000LL, 157.0f},
    {1699999760000LL, 157.5f},
    {1699999820000LL, 158.0f},
    {1699999880000LL, 158.5f},
    {1699999940000LL, 159.0f},
    {1700000000000LL, 159.5f},
};
static const gc_point_t oref_bolus_12[1] = {{0, 0.0f}};
static const float oref_expect_12[24] = {
    160.0f, 160.0f, 160.0f, 160.0f, 160.0f, 160.0f,
    160.0f, 160.0f, 160.0f, 160.0f, 160.0f, 160.0f,
    160.0f, 160.0f, 160.0f, 160.0f, 160.0f, 160.0f,
    160.0f, 160.0f, 160.0f, 160.0f, 160.0f, 160.0f,
};

static const gc_point_t oref_hist_13[8] = {
    {1699994300000LL, 120.0f},
    {1699994600000LL, 121.5f},
    {1699994900000LL, 123.0f},
    {1699995200000LL, 124.5f},
    {1699995500000LL, 126.0f},
    {1699995800000LL, 127.5f},
    {1699996100000LL, 129.0f},
    {1699996400000LL, 130.5f},
};
static const gc_point_t oref_bolus_13[1] = {{0, 0.0f}};
static const float oref_expect_13[24] = {
    130.0f, 130.0f, 130.0f, 130.0f, 130.0f, 130.0f,
    130.0f, 130.0f, 130.0f, 130.0f, 130.0f, 130.0f,
    130.0f, 130.0f, 130.0f, 130.0f, 130.0f, 130.0f,
    130.0f, 130.0f, 130.0f, 130.0f, 130.0f, 130.0f,
};

static const gc_point_t oref_hist_14[12] = {
    {1699996700000LL, 140.0f},
    {1699997000000LL, 140.0f},
    {1699997300000LL, 140.0f},
    {1699997600000LL, 140.0f},
    {1699997900000LL, 140.0f},
    {1699998200000LL, 140.0f},
    {1699998500000LL, 140.0f},
    {1699998800000LL, 140.0f},
    {1699999100000LL, 140.0f},
    {1699999400000LL, 140.0f},
    {1699999700000LL, 140.0f},
    {1700000000000LL, 140.0f},
};
static const gc_point_t oref_bolus_14[1] = {
    {1699998800000LL, 2.0f},
};
static const float oref_expect_14[24] = {
    138.01832575140816f, 135.6993431486763f, 133.0781676624308f, 130.1888678335118f, 127.06448767313228f, 123.73706865543701f,
    120.23767130919397f, 116.59639641524569f, 112.84240581624601f, 109.00394284510627f, 105.10835237847513f, 101.18210052147852f,
    97.25079392984874f, 93.33919877547723f, 89.47125936133085f, 85.67011639157975f, 81.95812490269307f, 78.3568718611695f,
    74.88719343348092f, 71.56919193372048f, 68.42225245436035f, 65.46505918544011f, 62.71561142742328f, 60.1912393028774f,
};

static const gc_point_t oref_hist_15[12] = {
    {1699996700000LL, 140.0f},
    {1699997000000LL, 140.0f},
    {1699997300000LL, 140.0f},
    {1699997600000LL, 140.0f},
    {1699997900000LL, 140.0f},
    {1699998200000LL, 140.0f},
    {1699998500000LL, 140.0f},
    {1699998800000LL, 140.0f},
    {1699999100000LL, 140.0f},
    {1699999400000LL, 140.0f},
    {1699999700000LL, 140.0f},
    {1700000000000LL, 140.0f},
};
static const gc_point_t oref_bolus_15[1] = {
    {1699998800000LL, 2.0f},
};
static const float oref_expect_15[24] = {
    138.01832575140816f, 135.6993431486763f, 133.0781676624308f, 130.1888678335118f, 127.06448767313228f, 123.73706865543701f,
    120.23767130919397f, 116.59639641524569f, 112.84240581624601f, 109.00394284510627f, 105.10835237847513f, 101.18210052147852f,
    97.25079392984874f, 93.33919877547723f, 89.47125936133085f, 85.67011639157975f, 81.95812490269307f, 78.3568718611695f,
    74.88719343348092f, 71.56919193372048f, 68.42225245436035f, 65.46505918544011f, 62.71561142742328f, 60.1912393028774f,
};

static const gc_point_t oref_hist_16[12] = {
    {1699996700000LL, 200.0f},
    {1699997000000LL, 200.0f},
    {1699997300000LL, 200.0f},
    {1699997600000LL, 200.0f},
    {1699997900000LL, 200.0f},
    {1699998200000LL, 200.0f},
    {1699998500000LL, 200.0f},
    {1699998800000LL, 200.0f},
    {1699999100000LL, 200.0f},
    {1699999400000LL, 200.0f},
    {1699999700000LL, 200.0f},
    {1700000000000LL, 200.0f},
};
static const gc_point_t oref_bolus_16[1] = {
    {1699988000000LL, 0.2f},
};
static const float oref_expect_16[24] = {
    196.66328408768035f, 192.07493123413678f, 186.32880029689707f, 179.50826418422153f, 171.68709035994436f, 162.930256671889f,
    153.29470689004154f, 142.83005005876146f, 131.57920750283367f, 119.57901107907051f, 106.86075603247531f, 93.45071159775067f,
    79.37059228230501f, 65.71199782660327f, 52.48880340012724f, 39.711533938099066f, 39.0f, 39.0f,
    39.0f, 39.0f, 39.0f, 39.0f, 39.0f, 39.0f,
};

static const gc_point_t oref_hist_17[12] = {
    {1699996700000LL, 200.0f},
    {1699997000000LL, 200.0f},
    {1699997300000LL, 200.0f},
    {1699997600000LL, 200.0f},
    {1699997900000LL, 200.0f},
    {1699998200000LL, 200.0f},
    {1699998500000LL, 200.0f},
    {1699998800000LL, 200.0f},
    {1699999100000LL, 200.0f},
    {1699999400000LL, 200.0f},
    {1699999700000LL, 200.0f},
    {1700000000000LL, 200.0f},
};
static const gc_point_t oref_bolus_17[2] = {
    {1699999400000LL, 9.0f},
    {1699998200000LL, 8.0f},
};
static const float oref_expect_17[24] = {
    196.6334129406977f, 192.71163190488645f, 188.31740826094085f, 183.52579118624192f, 178.4047260047631f, 173.01561045954568f,
    167.4138116930712f, 161.6491465338304f, 155.76632752332154f, 149.80537696365545f, 143.80201112130368f, 137.7879965867421f,
    131.79148066228552f, 125.83729753078282f, 119.94725184558071f, 114.14038127682379f, 108.43319945032826f, 102.83992062255234f,
    97.37266734822326f, 92.04166231562111f, 86.85540544803916f, 81.82083729823093f, 76.94348969542922f, 72.22762454150876f,
};

const gc_oref_vector_t gc_oref_vectors[] = {
    {
        .name = "flat_nothing_known",
        .sgv = 120.0f,
        .history = oref_hist_0, .history_count = 12,
        .boluses = oref_bolus_0, .bolus_count = 0,
        .has_pump_iob = false, .pump_iob = 0.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_0, .expected_count = 24,
        .expected_curve = GC_CURVE_IOB,
    },
    {
        .name = "flat_with_two_boluses",
        .sgv = 142.0f,
        .history = oref_hist_1, .history_count = 12,
        .boluses = oref_bolus_1, .bolus_count = 2,
        .has_pump_iob = true, .pump_iob = 2.4f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_1, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "pump_iob_but_no_visible_boluses",
        .sgv = 175.0f,
        .history = oref_hist_2, .history_count = 10,
        .boluses = oref_bolus_2, .bolus_count = 0,
        .has_pump_iob = true, .pump_iob = 3.2f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_2, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "negative_pump_iob",
        .sgv = 88.0f,
        .history = oref_hist_3, .history_count = 10,
        .boluses = oref_bolus_3, .bolus_count = 0,
        .has_pump_iob = true, .pump_iob = -0.8f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_3, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "carbs_on_board",
        .sgv = 134.0f,
        .history = oref_hist_4, .history_count = 12,
        .boluses = oref_bolus_4, .bolus_count = 1,
        .has_pump_iob = true, .pump_iob = 3.8f,
        .has_cob = true, .cob = 45.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_4, .expected_count = 24,
        .expected_curve = GC_CURVE_COB,
    },
    {
        .name = "carbs_on_board_tiny",
        .sgv = 101.0f,
        .history = oref_hist_5, .history_count = 12,
        .boluses = oref_bolus_5, .bolus_count = 0,
        .has_pump_iob = false, .pump_iob = 0.0f,
        .has_cob = true, .cob = 3.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_5, .expected_count = 24,
        .expected_curve = GC_CURVE_COB,
    },
    {
        .name = "rising_hard_unannounced_meal",
        .sgv = 196.0f,
        .history = oref_hist_6, .history_count = 10,
        .boluses = oref_bolus_6, .bolus_count = 0,
        .has_pump_iob = true, .pump_iob = 0.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_6, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "falling_into_the_low_clamp",
        .sgv = 62.0f,
        .history = oref_hist_7, .history_count = 10,
        .boluses = oref_bolus_7, .bolus_count = 1,
        .has_pump_iob = true, .pump_iob = 5.4f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_7, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "high_and_climbing_into_the_top_clamp",
        .sgv = 352.0f,
        .history = oref_hist_8, .history_count = 10,
        .boluses = oref_bolus_8, .bolus_count = 0,
        .has_pump_iob = false, .pump_iob = 0.0f,
        .has_cob = true, .cob = 120.0f,
        .params = {.isf = 20.0f, .has_isf = true, .cr = 4.0f, .has_cr = true, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_8, .expected_count = 24,
        .expected_curve = GC_CURVE_COB,
    },
    {
        .name = "implausible_profile_falls_back_to_defaults",
        .sgv = 150.0f,
        .history = oref_hist_9, .history_count = 12,
        .boluses = oref_bolus_9, .bolus_count = 1,
        .has_pump_iob = true, .pump_iob = 2.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.isf = 720.0f, .has_isf = true, .cr = 200.0f, .has_cr = true, .dia_hours = 0.5f, .has_dia_hours = true, .peak_min = 900.0f, .has_peak_min = true},
        .steps = 24,
        .expected = oref_expect_9, .expected_count = 24,
        .expected_curve = GC_CURVE_IOB,
    },
    {
        .name = "custom_but_plausible_profile",
        .sgv = 150.0f,
        .history = oref_hist_10, .history_count = 12,
        .boluses = oref_bolus_10, .bolus_count = 1,
        .has_pump_iob = true, .pump_iob = 2.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.isf = 35.0f, .has_isf = true, .cr = 8.0f, .has_cr = true, .dia_hours = 5.0f, .has_dia_hours = true, .peak_min = 55.0f, .has_peak_min = true},
        .steps = 24,
        .expected = oref_expect_10, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "gappy_history_skips_wide_pairs",
        .sgv = 145.0f,
        .history = oref_hist_11, .history_count = 4,
        .boluses = oref_bolus_11, .bolus_count = 0,
        .has_pump_iob = false, .pump_iob = 0.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_11, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "one_minute_cadence_skips_narrow_pairs",
        .sgv = 160.0f,
        .history = oref_hist_12, .history_count = 20,
        .boluses = oref_bolus_12, .bolus_count = 0,
        .has_pump_iob = false, .pump_iob = 0.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_12, .expected_count = 24,
        .expected_curve = GC_CURVE_IOB,
    },
    {
        .name = "history_older_than_the_deviation_window",
        .sgv = 130.0f,
        .history = oref_hist_13, .history_count = 8,
        .boluses = oref_bolus_13, .bolus_count = 0,
        .has_pump_iob = false, .pump_iob = 0.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_13, .expected_count = 24,
        .expected_curve = GC_CURVE_IOB,
    },
    {
        .name = "peak_at_half_the_duration",
        .sgv = 140.0f,
        .history = oref_hist_14, .history_count = 12,
        .boluses = oref_bolus_14, .bolus_count = 1,
        .has_pump_iob = true, .pump_iob = 1.8f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .dia_hours = 3.0f, .has_dia_hours = true, .peak_min = 90.0f, .has_peak_min = true},
        .steps = 24,
        .expected = oref_expect_14, .expected_count = 24,
        .expected_curve = GC_CURVE_IOB,
    },
    {
        .name = "peak_past_half_the_duration",
        .sgv = 140.0f,
        .history = oref_hist_15, .history_count = 12,
        .boluses = oref_bolus_15, .bolus_count = 1,
        .has_pump_iob = true, .pump_iob = 1.8f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .dia_hours = 3.0f, .has_dia_hours = true, .peak_min = 120.0f, .has_peak_min = true},
        .steps = 24,
        .expected = oref_expect_15, .expected_count = 24,
        .expected_curve = GC_CURVE_IOB,
    },
    {
        .name = "scale_clamped_at_the_ceiling",
        .sgv = 200.0f,
        .history = oref_hist_16, .history_count = 12,
        .boluses = oref_bolus_16, .bolus_count = 1,
        .has_pump_iob = true, .pump_iob = 9.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_16, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "scale_clamped_at_the_floor",
        .sgv = 200.0f,
        .history = oref_hist_17, .history_count = 12,
        .boluses = oref_bolus_17, .bolus_count = 2,
        .has_pump_iob = true, .pump_iob = 0.4f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_17, .expected_count = 24,
        .expected_curve = GC_CURVE_IOB,
    },
};
const int gc_oref_vector_count = 18;

static const gc_point_t pred_hist_0[12] = {
    {1699996700000LL, 140.0f},
    {1699997000000LL, 140.0f},
    {1699997300000LL, 140.0f},
    {1699997600000LL, 140.0f},
    {1699997900000LL, 140.0f},
    {1699998200000LL, 140.0f},
    {1699998500000LL, 140.0f},
    {1699998800000LL, 140.0f},
    {1699999100000LL, 140.0f},
    {1699999400000LL, 140.0f},
    {1699999700000LL, 140.0f},
    {1700000000000LL, 140.0f},
};
static const gc_point_t pred_bolus_0[1] = {{0, 0.0f}};
static const gc_point_t pred_series_0[24] = {
    {1700000120000LL, 138.0f},
    {1700000420000LL, 135.0f},
    {1700000720000LL, 131.0f},
    {1700001020000LL, 128.0f},
    {1700001320000LL, 125.0f},
    {1700001620000LL, 123.0f},
    {1700001920000LL, 121.0f},
    {1700002220000LL, 120.0f},
    {1700002520000LL, 120.0f},
    {1700002820000LL, 119.0f},
    {1700003120000LL, 119.0f},
    {1700003420000LL, 118.0f},
    {1700003720000LL, 118.0f},
    {1700004020000LL, 118.0f},
    {1700004320000LL, 118.0f},
    {1700004620000LL, 118.0f},
    {1700004920000LL, 118.0f},
    {1700005220000LL, 118.0f},
    {1700005520000LL, 118.0f},
    {1700005820000LL, 118.0f},
    {1700006120000LL, 118.0f},
    {1700006420000LL, 118.0f},
    {1700006720000LL, 118.0f},
    {1700007020000LL, 118.0f},
};
static const float pred_device_0[26] = {
    140.0f, 138.0f, 135.0f, 131.0f, 128.0f, 125.0f,
    123.0f, 121.0f, 120.0f, 120.0f, 119.0f, 119.0f,
    118.0f, 118.0f, 118.0f, 118.0f, 118.0f, 118.0f,
    118.0f, 118.0f, 118.0f, 118.0f, 118.0f, 118.0f,
    118.0f, 118.0f,
};

const gc_point_t *gc_pred_hist_0 = pred_hist_0;
const gc_point_t *gc_pred_bolus_0 = pred_bolus_0;
const float *gc_pred_device_0 = pred_device_0;

static const gc_point_t pred_hist_1[12] = {
    {1699996700000LL, 140.0f},
    {1699997000000LL, 140.0f},
    {1699997300000LL, 140.0f},
    {1699997600000LL, 140.0f},
    {1699997900000LL, 140.0f},
    {1699998200000LL, 140.0f},
    {1699998500000LL, 140.0f},
    {1699998800000LL, 140.0f},
    {1699999100000LL, 140.0f},
    {1699999400000LL, 140.0f},
    {1699999700000LL, 140.0f},
    {1700000000000LL, 140.0f},
};
static const gc_point_t pred_bolus_1[1] = {{0, 0.0f}};
static const gc_point_t pred_series_1[24] = {
    {1700000300000LL, 138.19724678545865f},
    {1700000600000LL, 136.37475671650864f},
    {1700000900000LL, 134.54295855509753f},
    {1700001200000LL, 132.71111595769864f},
    {1700001500000LL, 130.88742530918248f},
    {1700001800000LL, 129.0791063704183f},
    {1700002100000LL, 127.2924862269601f},
    {1700002400000LL, 125.53307699484785f},
    {1700002700000LL, 123.80564771016874f},
    {1700003000000LL, 122.11429080145749f},
    {1700003300000LL, 120.4624835181589f},
    {1700003600000LL, 118.85314466412883f},
    {1700003900000LL, 117.28868696241265f},
    {1700004200000LL, 115.77106535622357f},
    {1700004500000LL, 114.30182153105957f},
    {1700004800000LL, 112.88212492416756f},
    {1700005100000LL, 111.51281047000987f},
    {1700005400000LL, 110.19441331394034f},
    {1700005700000LL, 108.92720071088738f},
    {1700006000000LL, 107.71120131140621f},
    {1700006300000LL, 106.54623202394343f},
    {1700006600000LL, 105.43192262949587f},
    {1700006900000LL, 104.36773831299273f},
    {1700007200000LL, 103.35300026463281f},
};

const gc_point_t *gc_pred_hist_1 = pred_hist_1;
const gc_point_t *gc_pred_bolus_1 = pred_bolus_1;
const float *gc_pred_device_1 = NULL;

static const gc_point_t pred_hist_2[12] = {
    {1699996700000LL, 150.0f},
    {1699997000000LL, 150.5f},
    {1699997300000LL, 151.0f},
    {1699997600000LL, 151.5f},
    {1699997900000LL, 152.0f},
    {1699998200000LL, 152.5f},
    {1699998500000LL, 153.0f},
    {1699998800000LL, 153.5f},
    {1699999100000LL, 154.0f},
    {1699999400000LL, 154.5f},
    {1699999700000LL, 155.0f},
    {1700000000000LL, 155.5f},
};
static const gc_point_t pred_bolus_2[1] = {{0, 0.0f}};
static const gc_point_t pred_series_2[24] = {
    {1700000240000LL, 158.0f},
    {1700000540000LL, 161.0f},
    {1700000840000LL, 163.0f},
    {1700001140000LL, 164.0f},
    {1700001440000LL, 165.0f},
    {1700001740000LL, 165.0f},
    {1700002040000LL, 164.0f},
    {1700002340000LL, 163.0f},
    {1700002640000LL, 161.0f},
    {1700002940000LL, 160.0f},
    {1700003240000LL, 158.0f},
    {1700003540000LL, 157.0f},
    {1700003840000LL, 156.0f},
    {1700004140000LL, 155.0f},
    {1700004440000LL, 154.0f},
    {1700004740000LL, 153.0f},
    {1700005040000LL, 152.0f},
    {1700005340000LL, 151.0f},
    {1700005640000LL, 150.0f},
    {1700005940000LL, 149.0f},
    {1700006240000LL, 148.0f},
    {1700006540000LL, 147.0f},
    {1700006840000LL, 146.0f},
    {1700007140000LL, 145.0f},
};
static const float pred_device_2[25] = {
    155.0f, 158.0f, 161.0f, 163.0f, 164.0f, 165.0f,
    165.0f, 164.0f, 163.0f, 161.0f, 160.0f, 158.0f,
    157.0f, 156.0f, 155.0f, 154.0f, 153.0f, 152.0f,
    151.0f, 150.0f, 149.0f, 148.0f, 147.0f, 146.0f,
    145.0f,
};

const gc_point_t *gc_pred_hist_2 = pred_hist_2;
const gc_point_t *gc_pred_bolus_2 = pred_bolus_2;
const float *gc_pred_device_2 = pred_device_2;

static const gc_point_t pred_hist_3[1] = {{0, 0.0f}};
static const gc_point_t pred_bolus_3[1] = {{0, 0.0f}};
static const gc_point_t pred_series_3[1] = {{0, 0.0f}};

const gc_point_t *gc_pred_hist_3 = pred_hist_3;
const gc_point_t *gc_pred_bolus_3 = pred_bolus_3;
const float *gc_pred_device_3 = NULL;

static const gc_point_t pred_hist_4[6] = {
    {1699995800000LL, 120.0f},
    {1699996100000LL, 120.0f},
    {1699996400000LL, 120.0f},
    {1699996700000LL, 120.0f},
    {1699997000000LL, 120.0f},
    {1699997300000LL, 120.0f},
};
static const gc_point_t pred_bolus_4[1] = {{0, 0.0f}};
static const gc_point_t pred_series_4[1] = {{0, 0.0f}};

const gc_point_t *gc_pred_hist_4 = pred_hist_4;
const gc_point_t *gc_pred_bolus_4 = pred_bolus_4;
const float *gc_pred_device_4 = NULL;

static const gc_point_t pred_hist_5[12] = {
    {1699996700000LL, 118.0f},
    {1699997000000LL, 118.0f},
    {1699997300000LL, 118.0f},
    {1699997600000LL, 118.0f},
    {1699997900000LL, 118.0f},
    {1699998200000LL, 118.0f},
    {1699998500000LL, 118.0f},
    {1699998800000LL, 118.0f},
    {1699999100000LL, 118.0f},
    {1699999400000LL, 118.0f},
    {1699999700000LL, 118.0f},
    {1700000000000LL, 118.0f},
};
static const gc_point_t pred_bolus_5[1] = {
    {1699997900000LL, 2.0f},
};
static const gc_point_t pred_series_5[24] = {
    {1700000300000LL, 115.94143125809452f},
    {1700000600000LL, 113.75466037330996f},
    {1700000900000LL, 111.4644230362962f},
    {1700001200000LL, 109.09300827575336f},
    {1700001500000LL, 106.66045391179392f},
    {1700001800000LL, 104.1847280431773f},
    {1700002100000LL, 101.68189749898418f},
    {1700002400000LL, 99.1662841262222f},
    {1700002700000LL, 96.65060972939796f},
    {1700003000000LL, 94.1461304260373f},
    {1700003300000LL, 91.66276113328203f},
    {1700003600000LL, 89.20919085484749f},
    {1700003900000LL, 86.79298939460968f},
    {1700004200000LL, 84.42070608273438f},
    {1700004500000LL, 82.09796106240434f},
    {1700004800000LL, 79.82952964969314f},
    {1700005100000LL, 77.61942024583568f},
    {1700005400000LL, 75.47094624992013f},
    {1700005700000LL, 73.38679239075215f},
    {1700006000000LL, 71.36907586919864f},
    {1700006300000LL, 69.41940267659582f},
    {1700006600000LL, 67.53891943070055f},
    {1700006900000LL, 65.72836104807561f},
    {1700007200000LL, 63.98809455063746f},
};

const gc_point_t *gc_pred_hist_5 = pred_hist_5;
const gc_point_t *gc_pred_bolus_5 = pred_bolus_5;
const float *gc_pred_device_5 = NULL;

const gc_predict_vector_t gc_predict_vectors[] = {
    {
        .name = "device_curve_fresh",
        .snapshot = {
            .has_sgv = true, .sgv = 140.0f, .sgv_date = 1699999880000LL,
            .history = {{0, 0.0f}}, .history_count = 12,
            .boluses = {{0, 0.0f}}, .bolus_count = 0,
            .has_iob = true, .iob = 1.0f,
            .has_cob = true, .cob = 0.0f,
            .has_status = true, .status_date = 1699999820000LL,
            .device_pred = {.valid = true, .start_ms = 1699999820000LL, .count = 26},
            .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        },
        .expect_valid = true,
        .expect_estimated = false,
        .horizon_valid = {true, true, true, true},
        .horizons = {121.0f, 118.0f, 118.0f, 118.0f},
        .series_count = 24,
        .series = pred_series_0,
    },
    {
        .name = "device_curve_stale_falls_back",
        .snapshot = {
            .has_sgv = true, .sgv = 140.0f, .sgv_date = 1699999880000LL,
            .history = {{0, 0.0f}}, .history_count = 12,
            .boluses = {{0, 0.0f}}, .bolus_count = 0,
            .has_iob = true, .iob = 1.0f,
            .has_cob = true, .cob = 0.0f,
            .has_status = true, .status_date = 1699997600000LL,
            .device_pred = {.valid = false},
            .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        },
        .expect_valid = true,
        .expect_estimated = true,
        .horizon_valid = {true, true, true, true},
        .horizons = {129.0791063704183f, 118.85314466412883f, 110.19441331394034f, 103.35300026463281f},
        .series_count = 24,
        .series = pred_series_1,
    },
    {
        .name = "loop_style_curve",
        .snapshot = {
            .has_sgv = true, .sgv = 155.0f, .sgv_date = 1699999940000LL,
            .history = {{0, 0.0f}}, .history_count = 12,
            .boluses = {{0, 0.0f}}, .bolus_count = 0,
            .has_iob = true, .iob = 0.5f,
            .has_cob = true, .cob = 12.0f,
            .has_status = true, .status_date = 1699999940000LL,
            .device_pred = {.valid = true, .start_ms = 1699999940000LL, .count = 25},
            .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        },
        .expect_valid = true,
        .expect_estimated = false,
        .horizon_valid = {true, true, true, true},
        .horizons = {165.0f, 157.0f, 151.0f, 145.0f},
        .series_count = 24,
        .series = pred_series_2,
    },
    {
        .name = "no_reading_at_all",
        .snapshot = {
            .has_sgv = false, .sgv = 0.0f, .sgv_date = 0LL,
            .history = {{0, 0.0f}}, .history_count = 0,
            .boluses = {{0, 0.0f}}, .bolus_count = 0,
            .has_iob = false, .iob = 0.0f,
            .has_cob = false, .cob = 0.0f,
            .has_status = false, .status_date = 0LL,
            .device_pred = {.valid = false},
            .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        },
        .expect_valid = false,
        .expect_estimated = false,
        .horizon_valid = {false, false, false, false},
        .horizons = {0.0f, 0.0f, 0.0f, 0.0f},
        .series_count = 0,
        .series = pred_series_3,
    },
    {
        .name = "reading_too_old_to_forecast",
        .snapshot = {
            .has_sgv = true, .sgv = 120.0f, .sgv_date = 1699997300000LL,
            .history = {{0, 0.0f}}, .history_count = 6,
            .boluses = {{0, 0.0f}}, .bolus_count = 0,
            .has_iob = false, .iob = 0.0f,
            .has_cob = false, .cob = 0.0f,
            .has_status = false, .status_date = 0LL,
            .device_pred = {.valid = false},
            .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        },
        .expect_valid = false,
        .expect_estimated = false,
        .horizon_valid = {false, false, false, false},
        .horizons = {0.0f, 0.0f, 0.0f, 0.0f},
        .series_count = 0,
        .series = pred_series_4,
    },
    {
        .name = "estimate_from_a_fresh_reading",
        .snapshot = {
            .has_sgv = true, .sgv = 118.0f, .sgv_date = 1699999760000LL,
            .history = {{0, 0.0f}}, .history_count = 12,
            .boluses = {{0, 0.0f}}, .bolus_count = 1,
            .has_iob = true, .iob = 1.6f,
            .has_cob = true, .cob = 0.0f,
            .has_status = false, .status_date = 0LL,
            .device_pred = {.valid = false},
            .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        },
        .expect_valid = true,
        .expect_estimated = true,
        .horizon_valid = {true, true, true, true},
        .horizons = {104.1847280431773f, 89.20919085484749f, 75.47094624992013f, 63.98809455063746f},
        .series_count = 24,
        .series = pred_series_5,
    },
};
const int gc_predict_vector_count = 6;

const gc_version_vector_t gc_version_vectors[] = {
    {"2.0.1", "2.0.0", true},
    {"2.0.0", "2.0.1", false},
    {"2.0.0", "2.0.0", false},
    {"2.0.1", "2.0.1-rc.3", true},
    {"2.0.1-rc.3", "2.0.1", false},
    {"2.0.1-rc.4", "2.0.1-rc.3", true},
    {"2.0.1-rc.3", "2.0.1-rc.4", false},
    {"2.0.0-rc.1", "2.0.0-beta5", true},
    {"2.0.0-beta2", "2.0.0-alpha3", true},
    {"2.0.0-pre1", "2.0.0-alpha9", true},
    {"1.0", "1.0.0", false},
    {"1.0.0", "1.0", false},
    {"1.0.1", "1.0", true},
    {"v2.1.0", "2.0.9", true},
    {"2.1.0", "v2.0.9", true},
    {"3.0.0", "2.99.99", true},
    {"10.0.0", "9.99.99", true},
    {"2.0.10", "2.0.9", true},
    {"banana", "2.0.0", false},
    {"2.0.0", "banana", false},
    {"", "2.0.0", false},
    {"2.0.0-dev", "1.0.0", false},
    {"1.0.0", "2.0.0-dev", false},
    {"2.0.0", "0.0.0", true},
};
const int gc_version_vector_count = 24;

const gc_prerelease_vector_t gc_prerelease_vectors[] = {
    {"2.0.0", false},
    {"2.0.1-rc.3", true},
    {"v2.0.1-rc.3", true},
    {"2.0.0-beta2", true},
    {"2.0.0-alpha1", true},
    {"2.0.0-pre1", true},
    {"1.0", false},
    {"banana", false},
    {"", false},
    {"2.0.0-dev", false},
};
const int gc_prerelease_vector_count = 10;

const gc_point_t *gc_predict_history(int index) {
    switch (index) {
    case 0: return gc_pred_hist_0;
    case 1: return gc_pred_hist_1;
    case 2: return gc_pred_hist_2;
    case 3: return gc_pred_hist_3;
    case 4: return gc_pred_hist_4;
    case 5: return gc_pred_hist_5;
    default: return NULL;
    }
}

const gc_point_t *gc_predict_boluses(int index) {
    switch (index) {
    case 0: return gc_pred_bolus_0;
    case 1: return gc_pred_bolus_1;
    case 2: return gc_pred_bolus_2;
    case 3: return gc_pred_bolus_3;
    case 4: return gc_pred_bolus_4;
    case 5: return gc_pred_bolus_5;
    default: return NULL;
    }
}

const float *gc_predict_device_values(int index) {
    switch (index) {
    case 0: return gc_pred_device_0;
    case 1: return gc_pred_device_1;
    case 2: return gc_pred_device_2;
    case 3: return gc_pred_device_3;
    case 4: return gc_pred_device_4;
    case 5: return gc_pred_device_5;
    default: return NULL;
    }
}
