/*
 * Generated by firmware/host_test/gen_vectors.py — do not edit by hand.
 */

#include "vectors.h"

static const gc_point_t oref_hist_0[12] = {
    {1699996700000LL, 120.0f},
    {1699997000000LL, 120.0f},
    {1699997300000LL, 120.0f},
    {1699997600000LL, 120.0f},
    {1699997900000LL, 120.0f},
    {1699998200000LL, 120.0f},
    {1699998500000LL, 120.0f},
    {1699998800000LL, 120.0f},
    {1699999100000LL, 120.0f},
    {1699999400000LL, 120.0f},
    {1699999700000LL, 120.0f},
    {1700000000000LL, 120.0f},
};
static const gc_point_t oref_bolus_0[1] = {{0, 0.0f}};
static const float oref_expect_0[24] = {
    120.0f, 120.0f, 120.0f, 120.0f, 120.0f, 120.0f,
    120.0f, 120.0f, 120.0f, 120.0f, 120.0f, 120.0f,
    120.0f, 120.0f, 120.0f, 120.0f, 120.0f, 120.0f,
    120.0f, 120.0f, 120.0f, 120.0f, 120.0f, 120.0f,
};

static const gc_point_t oref_hist_1[12] = {
    {1699996700000LL, 142.0f},
    {1699997000000LL, 142.0f},
    {1699997300000LL, 142.0f},
    {1699997600000LL, 142.0f},
    {1699997900000LL, 142.0f},
    {1699998200000LL, 142.0f},
    {1699998500000LL, 142.0f},
    {1699998800000LL, 142.0f},
    {1699999100000LL, 142.0f},
    {1699999400000LL, 142.0f},
    {1699999700000LL, 142.0f},
    {1700000000000LL, 142.0f},
};
static const gc_point_t oref_bolus_1[2] = {
    {1699994600000LL, 2.5f},
    {1699998500000LL, 1.2f},
};
static const float oref_expect_1[24] = {
    141.254302f, 140.155001f, 138.729066f, 137.000504f, 134.990614f, 132.718209f,
    130.199832f, 127.44995f, 124.481137f, 121.304241f, 117.92854f, 114.361886f,
    110.610838f, 106.968056f, 103.437867f, 100.023643f, 96.727894f, 93.552361f,
    90.498092f, 87.565519f, 84.754528f, 82.064515f, 79.49445f, 77.042927f,
};

static const gc_point_t oref_hist_2[10] = {
    {1699997300000LL, 160.0f},
    {1699997600000LL, 161.5f},
    {1699997900000LL, 163.0f},
    {1699998200000LL, 164.5f},
    {1699998500000LL, 166.0f},
    {1699998800000LL, 167.5f},
    {1699999100000LL, 169.0f},
    {1699999400000LL, 170.5f},
    {1699999700000LL, 172.0f},
    {1700000000000LL, 173.5f},
};
static const gc_point_t oref_bolus_2[1] = {{0, 0.0f}};
static const float oref_expect_2[24] = {
    175.313612f, 175.057198f, 174.264129f, 172.964049f, 171.183188f, 168.944647f,
    166.268674f, 163.172907f, 159.672607f, 155.780871f, 151.508824f, 146.865809f,
    141.859544f, 137.003155f, 132.301575f, 127.758545f, 123.376739f, 119.157868f,
    115.102788f, 111.21159f, 107.483688f, 103.917898f, 100.512508f, 97.265346f,
};

static const gc_point_t oref_hist_3[10] = {
    {1699997300000LL, 100.0f},
    {1699997600000LL, 98.8f},
    {1699997900000LL, 97.6f},
    {1699998200000LL, 96.4f},
    {1699998500000LL, 95.2f},
    {1699998800000LL, 94.0f},
    {1699999100000LL, 92.8f},
    {1699999400000LL, 91.6f},
    {1699999700000LL, 90.4f},
    {1700000000000LL, 89.2f},
};
static const gc_point_t oref_bolus_3[1] = {{0, 0.0f}};
static const float oref_expect_3[24] = {
    87.096597f, 86.404451f, 85.915218f, 85.621488f, 85.516703f, 85.595088f,
    85.851582f, 86.281773f, 86.881848f, 87.648532f, 88.579044f, 89.671048f,
    90.922614f, 92.136711f, 93.312106f, 94.447864f, 95.543315f, 96.598033f,
    97.611803f, 98.584603f, 99.516578f, 100.408025f, 101.259373f, 102.071163f,
};

static const gc_point_t oref_hist_4[12] = {
    {1699996700000LL, 120.0f},
    {1699997000000LL, 121.2f},
    {1699997300000LL, 122.4f},
    {1699997600000LL, 123.6f},
    {1699997900000LL, 124.8f},
    {1699998200000LL, 126.0f},
    {1699998500000LL, 127.2f},
    {1699998800000LL, 128.4f},
    {1699999100000LL, 129.6f},
    {1699999400000LL, 130.8f},
    {1699999700000LL, 132.0f},
    {1700000000000LL, 133.2f},
};
static const gc_point_t oref_bolus_4[1] = {
    {1699998800000LL, 4.0f},
};
static const float oref_expect_4[24] = {
    138.656387f, 142.112175f, 144.44193f, 145.713238f, 145.987248f, 145.319179f,
    143.758785f, 141.350798f, 138.135327f, 134.14824f, 129.421506f, 123.983525f,
    118.392757f, 112.849113f, 107.371989f, 101.978285f, 96.682619f, 91.497538f,
    86.433701f, 81.500057f, 76.704002f, 72.05153f, 67.547366f, 63.195096f,
};

static const gc_point_t oref_hist_5[12] = {
    {1699996700000LL, 101.0f},
    {1699997000000LL, 101.0f},
    {1699997300000LL, 101.0f},
    {1699997600000LL, 101.0f},
    {1699997900000LL, 101.0f},
    {1699998200000LL, 101.0f},
    {1699998500000LL, 101.0f},
    {1699998800000LL, 101.0f},
    {1699999100000LL, 101.0f},
    {1699999400000LL, 101.0f},
    {1699999700000LL, 101.0f},
    {1700000000000LL, 101.0f},
};
static const gc_point_t oref_bolus_5[1] = {{0, 0.0f}};
static const float oref_expect_5[24] = {
    109.0f, 109.0f, 109.0f, 109.0f, 109.0f, 109.0f,
    109.0f, 109.0f, 109.0f, 109.0f, 109.0f, 109.0f,
    109.0f, 109.0f, 109.0f, 109.0f, 109.0f, 109.0f,
    109.0f, 109.0f, 109.0f, 109.0f, 109.0f, 109.0f,
};

static const gc_point_t oref_hist_6[10] = {
    {1699997300000LL, 150.0f},
    {1699997600000LL, 155.2f},
    {1699997900000LL, 160.4f},
    {1699998200000LL, 165.6f},
    {1699998500000LL, 170.8f},
    {1699998800000LL, 176.0f},
    {1699999100000LL, 181.2f},
    {1699999400000LL, 186.4f},
    {1699999700000LL, 191.6f},
    {1700000000000LL, 196.8f},
};
static const gc_point_t oref_bolus_6[1] = {{0, 0.0f}};
static const float oref_expect_6[24] = {
    201.2f, 205.966667f, 210.3f, 214.2f, 217.666667f, 220.7f,
    223.3f, 225.466667f, 227.2f, 228.5f, 229.366667f, 229.8f,
    229.8f, 229.8f, 229.8f, 229.8f, 229.8f, 229.8f,
    229.8f, 229.8f, 229.8f, 229.8f, 229.8f, 229.8f,
};

static const gc_point_t oref_hist_7[10] = {
    {1699997300000LL, 130.0f},
    {1699997600000LL, 122.5f},
    {1699997900000LL, 115.0f},
    {1699998200000LL, 107.5f},
    {1699998500000LL, 100.0f},
    {1699998800000LL, 92.5f},
    {1699999100000LL, 85.0f},
    {1699999400000LL, 77.5f},
    {1699999700000LL, 70.0f},
    {1700000000000LL, 62.5f},
};
static const gc_point_t oref_bolus_7[1] = {
    {1699998200000LL, 6.0f},
};
static const float oref_expect_7[24] = {
    50.505207f, 39.0f, 39.0f, 39.0f, 39.0f, 39.0f,
    39.0f, 39.0f, 39.0f, 39.0f, 39.0f, 39.0f,
    39.0f, 39.0f, 39.0f, 39.0f, 39.0f, 39.0f,
    39.0f, 39.0f, 39.0f, 39.0f, 39.0f, 39.0f,
};

static const gc_point_t oref_hist_8[10] = {
    {1699997300000LL, 300.0f},
    {1699997600000LL, 305.5f},
    {1699997900000LL, 311.0f},
    {1699998200000LL, 316.5f},
    {1699998500000LL, 322.0f},
    {1699998800000LL, 327.5f},
    {1699999100000LL, 333.0f},
    {1699999400000LL, 338.5f},
    {1699999700000LL, 344.0f},
    {1700000000000LL, 349.5f},
};
static const gc_point_t oref_bolus_8[1] = {{0, 0.0f}};
static const float oref_expect_8[24] = {
    360.0f, 367.733333f, 375.2f, 382.4f, 389.333333f, 396.0f,
    401.0f, 401.0f, 401.0f, 401.0f, 401.0f, 401.0f,
    401.0f, 401.0f, 401.0f, 401.0f, 401.0f, 401.0f,
    401.0f, 401.0f, 401.0f, 401.0f, 401.0f, 401.0f,
};

static const gc_point_t oref_hist_9[12] = {
    {1699996700000LL, 150.0f},
    {1699997000000LL, 150.0f},
    {1699997300000LL, 150.0f},
    {1699997600000LL, 150.0f},
    {1699997900000LL, 150.0f},
    {1699998200000LL, 150.0f},
    {1699998500000LL, 150.0f},
    {1699998800000LL, 150.0f},
    {1699999100000LL, 150.0f},
    {1699999400000LL, 150.0f},
    {1699999700000LL, 150.0f},
    {1700000000000LL, 150.0f},
};
static const gc_point_t oref_bolus_9[1] = {
    {1699997300000LL, 3.0f},
};
static const float oref_expect_9[24] = {
    146.976857f, 143.846559f, 140.635555f, 137.367565f, 134.063796f, 130.743154f,
    127.422431f, 124.116486f, 120.838406f, 117.599662f, 114.410244f, 111.2788f,
    108.212746f, 105.218387f, 102.301014f, 99.465001f, 96.71389f, 94.050479f,
    91.476885f, 88.994622f, 86.604662f, 84.307487f, 82.103151f, 79.991321f,
};

static const gc_point_t oref_hist_10[12] = {
    {1699996700000LL, 150.0f},
    {1699997000000LL, 150.0f},
    {1699997300000LL, 150.0f},
    {1699997600000LL, 150.0f},
    {1699997900000LL, 150.0f},
    {1699998200000LL, 150.0f},
    {1699998500000LL, 150.0f},
    {1699998800000LL, 150.0f},
    {1699999100000LL, 150.0f},
    {1699999400000LL, 150.0f},
    {1699999700000LL, 150.0f},
    {1700000000000LL, 150.0f},
};
static const gc_point_t oref_bolus_10[1] = {
    {1699997300000LL, 3.0f},
};
static const float oref_expect_10[24] = {
    148.871095f, 147.52688f, 145.999191f, 144.314855f, 142.496284f, 140.562006f,
    138.52713f, 136.403781f, 134.201471f, 131.927441f, 129.586963f, 127.183605f,
    124.719476f, 122.3787f, 120.161072f, 118.065492f, 116.090111f, 114.23246f,
    112.489565f, 110.858044f, 109.334199f, 107.914087f, 106.593588f, 105.368463f,
};

static const gc_point_t oref_hist_11[4] = {
    {1699997600000LL, 120.0f},
    {1699998500000LL, 132.0f},
    {1699998800000LL, 138.0f},
    {1699999700000LL, 145.0f},
};
static const gc_point_t oref_bolus_11[1] = {{0, 0.0f}};
static const float oref_expect_11[24] = {
    151.0f, 156.5f, 161.5f, 166.0f, 170.0f, 173.5f,
    176.5f, 179.0f, 181.0f, 182.5f, 183.5f, 184.0f,
    184.0f, 184.0f, 184.0f, 184.0f, 184.0f, 184.0f,
    184.0f, 184.0f, 184.0f, 184.0f, 184.0f, 184.0f,
};

static const gc_point_t oref_hist_12[20] = {
    {1699998860000LL, 150.0f},
    {1699998920000LL, 150.5f},
    {1699998980000LL, 151.0f},
    {1699999040000LL, 151.5f},
    {1699999100000LL, 152.0f},
    {1699999160000LL, 152.5f},
    {1699999220000LL, 153.0f},
    {1699999280000LL, 153.5f},
    {1699999340000LL, 154.0f},
    {1699999400000LL, 154.5f},
    {1699999460000LL, 155.0f},
    {1699999520000LL, 155.5f},
    {1699999580000LL, 156.0f},
    {1699999640000LL, 156.5f},
    {1699999700000LL, 157.0f},
    {1699999760000LL, 157.5f},
    {1699999820000LL, 158.0f},
    {1699999880000LL, 158.5f},
    {1699999940000LL, 159.0f},
    {1700000000000LL, 159.5f},
};
static const gc_point_t oref_bolus_12[1] = {{0, 0.0f}};
static const float oref_expect_12[24] = {
    160.0f, 160.0f, 160.0f, 160.0f, 160.0f, 160.0f,
    160.0f, 160.0f, 160.0f, 160.0f, 160.0f, 160.0f,
    160.0f, 160.0f, 160.0f, 160.0f, 160.0f, 160.0f,
    160.0f, 160.0f, 160.0f, 160.0f, 160.0f, 160.0f,
};

static const gc_point_t oref_hist_13[8] = {
    {1699994300000LL, 120.0f},
    {1699994600000LL, 121.5f},
    {1699994900000LL, 123.0f},
    {1699995200000LL, 124.5f},
    {1699995500000LL, 126.0f},
    {1699995800000LL, 127.5f},
    {1699996100000LL, 129.0f},
    {1699996400000LL, 130.5f},
};
static const gc_point_t oref_bolus_13[1] = {{0, 0.0f}};
static const float oref_expect_13[24] = {
    130.0f, 130.0f, 130.0f, 130.0f, 130.0f, 130.0f,
    130.0f, 130.0f, 130.0f, 130.0f, 130.0f, 130.0f,
    130.0f, 130.0f, 130.0f, 130.0f, 130.0f, 130.0f,
    130.0f, 130.0f, 130.0f, 130.0f, 130.0f, 130.0f,
};

static const gc_point_t oref_hist_14[12] = {
    {1699996700000LL, 140.0f},
    {1699997000000LL, 140.0f},
    {1699997300000LL, 140.0f},
    {1699997600000LL, 140.0f},
    {1699997900000LL, 140.0f},
    {1699998200000LL, 140.0f},
    {1699998500000LL, 140.0f},
    {1699998800000LL, 140.0f},
    {1699999100000LL, 140.0f},
    {1699999400000LL, 140.0f},
    {1699999700000LL, 140.0f},
    {1700000000000LL, 140.0f},
};
static const gc_point_t oref_bolus_14[1] = {
    {1699998800000LL, 2.0f},
};
static const float oref_expect_14[24] = {
    138.018326f, 135.699343f, 133.078168f, 130.188868f, 127.064488f, 123.737069f,
    120.237671f, 116.596396f, 112.842406f, 109.003943f, 105.108352f, 101.182101f,
    97.250794f, 93.339199f, 89.471259f, 85.670116f, 81.958125f, 78.356872f,
    74.887193f, 71.569192f, 68.422252f, 65.465059f, 62.715611f, 60.191239f,
};

static const gc_point_t oref_hist_15[12] = {
    {1699996700000LL, 140.0f},
    {1699997000000LL, 140.0f},
    {1699997300000LL, 140.0f},
    {1699997600000LL, 140.0f},
    {1699997900000LL, 140.0f},
    {1699998200000LL, 140.0f},
    {1699998500000LL, 140.0f},
    {1699998800000LL, 140.0f},
    {1699999100000LL, 140.0f},
    {1699999400000LL, 140.0f},
    {1699999700000LL, 140.0f},
    {1700000000000LL, 140.0f},
};
static const gc_point_t oref_bolus_15[1] = {
    {1699998800000LL, 2.0f},
};
static const float oref_expect_15[24] = {
    138.018326f, 135.699343f, 133.078168f, 130.188868f, 127.064488f, 123.737069f,
    120.237671f, 116.596396f, 112.842406f, 109.003943f, 105.108352f, 101.182101f,
    97.250794f, 93.339199f, 89.471259f, 85.670116f, 81.958125f, 78.356872f,
    74.887193f, 71.569192f, 68.422252f, 65.465059f, 62.715611f, 60.191239f,
};

static const gc_point_t oref_hist_16[12] = {
    {1699996700000LL, 200.0f},
    {1699997000000LL, 200.0f},
    {1699997300000LL, 200.0f},
    {1699997600000LL, 200.0f},
    {1699997900000LL, 200.0f},
    {1699998200000LL, 200.0f},
    {1699998500000LL, 200.0f},
    {1699998800000LL, 200.0f},
    {1699999100000LL, 200.0f},
    {1699999400000LL, 200.0f},
    {1699999700000LL, 200.0f},
    {1700000000000LL, 200.0f},
};
static const gc_point_t oref_bolus_16[1] = {
    {1699988000000LL, 0.2f},
};
static const float oref_expect_16[24] = {
    196.663284f, 192.074931f, 186.3288f, 179.508264f, 171.68709f, 162.930257f,
    153.294707f, 142.83005f, 131.579208f, 119.579011f, 106.860756f, 93.450712f,
    79.370592f, 65.711998f, 52.488803f, 39.711534f, 39.0f, 39.0f,
    39.0f, 39.0f, 39.0f, 39.0f, 39.0f, 39.0f,
};

static const gc_point_t oref_hist_17[12] = {
    {1699996700000LL, 200.0f},
    {1699997000000LL, 200.0f},
    {1699997300000LL, 200.0f},
    {1699997600000LL, 200.0f},
    {1699997900000LL, 200.0f},
    {1699998200000LL, 200.0f},
    {1699998500000LL, 200.0f},
    {1699998800000LL, 200.0f},
    {1699999100000LL, 200.0f},
    {1699999400000LL, 200.0f},
    {1699999700000LL, 200.0f},
    {1700000000000LL, 200.0f},
};
static const gc_point_t oref_bolus_17[2] = {
    {1699999400000LL, 9.0f},
    {1699998200000LL, 8.0f},
};
static const float oref_expect_17[24] = {
    196.633413f, 192.711632f, 188.317408f, 183.525791f, 178.404726f, 173.01561f,
    167.413812f, 161.649147f, 155.766328f, 149.805377f, 143.802011f, 137.787997f,
    131.791481f, 125.837298f, 119.947252f, 114.140381f, 108.433199f, 102.839921f,
    97.372667f, 92.041662f, 86.855405f, 81.820837f, 76.94349f, 72.227625f,
};

const gc_oref_vector_t gc_oref_vectors[] = {
    {
        .name = "flat_nothing_known",
        .sgv = 120.0f,
        .history = oref_hist_0, .history_count = 12,
        .boluses = oref_bolus_0, .bolus_count = 0,
        .has_pump_iob = false, .pump_iob = 0.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_0, .expected_count = 24,
        .expected_curve = GC_CURVE_IOB,
    },
    {
        .name = "flat_with_two_boluses",
        .sgv = 142.0f,
        .history = oref_hist_1, .history_count = 12,
        .boluses = oref_bolus_1, .bolus_count = 2,
        .has_pump_iob = true, .pump_iob = 2.4f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_1, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "pump_iob_but_no_visible_boluses",
        .sgv = 175.0f,
        .history = oref_hist_2, .history_count = 10,
        .boluses = oref_bolus_2, .bolus_count = 0,
        .has_pump_iob = true, .pump_iob = 3.2f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_2, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "negative_pump_iob",
        .sgv = 88.0f,
        .history = oref_hist_3, .history_count = 10,
        .boluses = oref_bolus_3, .bolus_count = 0,
        .has_pump_iob = true, .pump_iob = -0.8f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_3, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "carbs_on_board",
        .sgv = 134.0f,
        .history = oref_hist_4, .history_count = 12,
        .boluses = oref_bolus_4, .bolus_count = 1,
        .has_pump_iob = true, .pump_iob = 3.8f,
        .has_cob = true, .cob = 45.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_4, .expected_count = 24,
        .expected_curve = GC_CURVE_COB,
    },
    {
        .name = "carbs_on_board_tiny",
        .sgv = 101.0f,
        .history = oref_hist_5, .history_count = 12,
        .boluses = oref_bolus_5, .bolus_count = 0,
        .has_pump_iob = false, .pump_iob = 0.0f,
        .has_cob = true, .cob = 3.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_5, .expected_count = 24,
        .expected_curve = GC_CURVE_COB,
    },
    {
        .name = "rising_hard_unannounced_meal",
        .sgv = 196.0f,
        .history = oref_hist_6, .history_count = 10,
        .boluses = oref_bolus_6, .bolus_count = 0,
        .has_pump_iob = true, .pump_iob = 0.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_6, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "falling_into_the_low_clamp",
        .sgv = 62.0f,
        .history = oref_hist_7, .history_count = 10,
        .boluses = oref_bolus_7, .bolus_count = 1,
        .has_pump_iob = true, .pump_iob = 5.4f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_7, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "high_and_climbing_into_the_top_clamp",
        .sgv = 352.0f,
        .history = oref_hist_8, .history_count = 10,
        .boluses = oref_bolus_8, .bolus_count = 0,
        .has_pump_iob = false, .pump_iob = 0.0f,
        .has_cob = true, .cob = 120.0f,
        .params = {.isf = 20.0f, .has_isf = true, .cr = 4.0f, .has_cr = true, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_8, .expected_count = 24,
        .expected_curve = GC_CURVE_COB,
    },
    {
        .name = "implausible_profile_falls_back_to_defaults",
        .sgv = 150.0f,
        .history = oref_hist_9, .history_count = 12,
        .boluses = oref_bolus_9, .bolus_count = 1,
        .has_pump_iob = true, .pump_iob = 2.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.isf = 720.0f, .has_isf = true, .cr = 200.0f, .has_cr = true, .dia_hours = 0.5f, .has_dia_hours = true, .peak_min = 900.0f, .has_peak_min = true},
        .steps = 24,
        .expected = oref_expect_9, .expected_count = 24,
        .expected_curve = GC_CURVE_IOB,
    },
    {
        .name = "custom_but_plausible_profile",
        .sgv = 150.0f,
        .history = oref_hist_10, .history_count = 12,
        .boluses = oref_bolus_10, .bolus_count = 1,
        .has_pump_iob = true, .pump_iob = 2.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.isf = 35.0f, .has_isf = true, .cr = 8.0f, .has_cr = true, .dia_hours = 5.0f, .has_dia_hours = true, .peak_min = 55.0f, .has_peak_min = true},
        .steps = 24,
        .expected = oref_expect_10, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "gappy_history_skips_wide_pairs",
        .sgv = 145.0f,
        .history = oref_hist_11, .history_count = 4,
        .boluses = oref_bolus_11, .bolus_count = 0,
        .has_pump_iob = false, .pump_iob = 0.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_11, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "one_minute_cadence_skips_narrow_pairs",
        .sgv = 160.0f,
        .history = oref_hist_12, .history_count = 20,
        .boluses = oref_bolus_12, .bolus_count = 0,
        .has_pump_iob = false, .pump_iob = 0.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_12, .expected_count = 24,
        .expected_curve = GC_CURVE_IOB,
    },
    {
        .name = "history_older_than_the_deviation_window",
        .sgv = 130.0f,
        .history = oref_hist_13, .history_count = 8,
        .boluses = oref_bolus_13, .bolus_count = 0,
        .has_pump_iob = false, .pump_iob = 0.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_13, .expected_count = 24,
        .expected_curve = GC_CURVE_IOB,
    },
    {
        .name = "peak_at_half_the_duration",
        .sgv = 140.0f,
        .history = oref_hist_14, .history_count = 12,
        .boluses = oref_bolus_14, .bolus_count = 1,
        .has_pump_iob = true, .pump_iob = 1.8f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .dia_hours = 3.0f, .has_dia_hours = true, .peak_min = 90.0f, .has_peak_min = true},
        .steps = 24,
        .expected = oref_expect_14, .expected_count = 24,
        .expected_curve = GC_CURVE_IOB,
    },
    {
        .name = "peak_past_half_the_duration",
        .sgv = 140.0f,
        .history = oref_hist_15, .history_count = 12,
        .boluses = oref_bolus_15, .bolus_count = 1,
        .has_pump_iob = true, .pump_iob = 1.8f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .dia_hours = 3.0f, .has_dia_hours = true, .peak_min = 120.0f, .has_peak_min = true},
        .steps = 24,
        .expected = oref_expect_15, .expected_count = 24,
        .expected_curve = GC_CURVE_IOB,
    },
    {
        .name = "scale_clamped_at_the_ceiling",
        .sgv = 200.0f,
        .history = oref_hist_16, .history_count = 12,
        .boluses = oref_bolus_16, .bolus_count = 1,
        .has_pump_iob = true, .pump_iob = 9.0f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_16, .expected_count = 24,
        .expected_curve = GC_CURVE_UAM,
    },
    {
        .name = "scale_clamped_at_the_floor",
        .sgv = 200.0f,
        .history = oref_hist_17, .history_count = 12,
        .boluses = oref_bolus_17, .bolus_count = 2,
        .has_pump_iob = true, .pump_iob = 0.4f,
        .has_cob = false, .cob = 0.0f,
        .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        .steps = 24,
        .expected = oref_expect_17, .expected_count = 24,
        .expected_curve = GC_CURVE_IOB,
    },
};
const int gc_oref_vector_count = 18;

static const gc_point_t pred_hist_0[12] = {
    {1699996700000LL, 140.0f},
    {1699997000000LL, 140.0f},
    {1699997300000LL, 140.0f},
    {1699997600000LL, 140.0f},
    {1699997900000LL, 140.0f},
    {1699998200000LL, 140.0f},
    {1699998500000LL, 140.0f},
    {1699998800000LL, 140.0f},
    {1699999100000LL, 140.0f},
    {1699999400000LL, 140.0f},
    {1699999700000LL, 140.0f},
    {1700000000000LL, 140.0f},
};
static const gc_point_t pred_bolus_0[1] = {{0, 0.0f}};
static const gc_point_t pred_series_0[24] = {
    {1700000120000LL, 138.0f},
    {1700000420000LL, 135.0f},
    {1700000720000LL, 131.0f},
    {1700001020000LL, 128.0f},
    {1700001320000LL, 125.0f},
    {1700001620000LL, 123.0f},
    {1700001920000LL, 121.0f},
    {1700002220000LL, 120.0f},
    {1700002520000LL, 120.0f},
    {1700002820000LL, 119.0f},
    {1700003120000LL, 119.0f},
    {1700003420000LL, 118.0f},
    {1700003720000LL, 118.0f},
    {1700004020000LL, 118.0f},
    {1700004320000LL, 118.0f},
    {1700004620000LL, 118.0f},
    {1700004920000LL, 118.0f},
    {1700005220000LL, 118.0f},
    {1700005520000LL, 118.0f},
    {1700005820000LL, 118.0f},
    {1700006120000LL, 118.0f},
    {1700006420000LL, 118.0f},
    {1700006720000LL, 118.0f},
    {1700007020000LL, 118.0f},
};
static const float pred_device_0[26] = {
    140.0f, 138.0f, 135.0f, 131.0f, 128.0f, 125.0f,
    123.0f, 121.0f, 120.0f, 120.0f, 119.0f, 119.0f,
    118.0f, 118.0f, 118.0f, 118.0f, 118.0f, 118.0f,
    118.0f, 118.0f, 118.0f, 118.0f, 118.0f, 118.0f,
    118.0f, 118.0f,
};

const gc_point_t *gc_pred_hist_0 = pred_hist_0;
const gc_point_t *gc_pred_bolus_0 = pred_bolus_0;
const float *gc_pred_device_0 = pred_device_0;

static const gc_point_t pred_hist_1[12] = {
    {1699996700000LL, 140.0f},
    {1699997000000LL, 140.0f},
    {1699997300000LL, 140.0f},
    {1699997600000LL, 140.0f},
    {1699997900000LL, 140.0f},
    {1699998200000LL, 140.0f},
    {1699998500000LL, 140.0f},
    {1699998800000LL, 140.0f},
    {1699999100000LL, 140.0f},
    {1699999400000LL, 140.0f},
    {1699999700000LL, 140.0f},
    {1700000000000LL, 140.0f},
};
static const gc_point_t pred_bolus_1[1] = {{0, 0.0f}};
static const gc_point_t pred_series_1[24] = {
    {1700000300000LL, 138.197247f},
    {1700000600000LL, 136.374757f},
    {1700000900000LL, 134.542959f},
    {1700001200000LL, 132.711116f},
    {1700001500000LL, 130.887425f},
    {1700001800000LL, 129.079106f},
    {1700002100000LL, 127.292486f},
    {1700002400000LL, 125.533077f},
    {1700002700000LL, 123.805648f},
    {1700003000000LL, 122.114291f},
    {1700003300000LL, 120.462484f},
    {1700003600000LL, 118.853145f},
    {1700003900000LL, 117.288687f},
    {1700004200000LL, 115.771065f},
    {1700004500000LL, 114.301822f},
    {1700004800000LL, 112.882125f},
    {1700005100000LL, 111.51281f},
    {1700005400000LL, 110.194413f},
    {1700005700000LL, 108.927201f},
    {1700006000000LL, 107.711201f},
    {1700006300000LL, 106.546232f},
    {1700006600000LL, 105.431923f},
    {1700006900000LL, 104.367738f},
    {1700007200000LL, 103.353f},
};

const gc_point_t *gc_pred_hist_1 = pred_hist_1;
const gc_point_t *gc_pred_bolus_1 = pred_bolus_1;
const float *gc_pred_device_1 = NULL;

static const gc_point_t pred_hist_2[12] = {
    {1699996700000LL, 150.0f},
    {1699997000000LL, 150.5f},
    {1699997300000LL, 151.0f},
    {1699997600000LL, 151.5f},
    {1699997900000LL, 152.0f},
    {1699998200000LL, 152.5f},
    {1699998500000LL, 153.0f},
    {1699998800000LL, 153.5f},
    {1699999100000LL, 154.0f},
    {1699999400000LL, 154.5f},
    {1699999700000LL, 155.0f},
    {1700000000000LL, 155.5f},
};
static const gc_point_t pred_bolus_2[1] = {{0, 0.0f}};
static const gc_point_t pred_series_2[24] = {
    {1700000240000LL, 158.0f},
    {1700000540000LL, 161.0f},
    {1700000840000LL, 163.0f},
    {1700001140000LL, 164.0f},
    {1700001440000LL, 165.0f},
    {1700001740000LL, 165.0f},
    {1700002040000LL, 164.0f},
    {1700002340000LL, 163.0f},
    {1700002640000LL, 161.0f},
    {1700002940000LL, 160.0f},
    {1700003240000LL, 158.0f},
    {1700003540000LL, 157.0f},
    {1700003840000LL, 156.0f},
    {1700004140000LL, 155.0f},
    {1700004440000LL, 154.0f},
    {1700004740000LL, 153.0f},
    {1700005040000LL, 152.0f},
    {1700005340000LL, 151.0f},
    {1700005640000LL, 150.0f},
    {1700005940000LL, 149.0f},
    {1700006240000LL, 148.0f},
    {1700006540000LL, 147.0f},
    {1700006840000LL, 146.0f},
    {1700007140000LL, 145.0f},
};
static const float pred_device_2[25] = {
    155.0f, 158.0f, 161.0f, 163.0f, 164.0f, 165.0f,
    165.0f, 164.0f, 163.0f, 161.0f, 160.0f, 158.0f,
    157.0f, 156.0f, 155.0f, 154.0f, 153.0f, 152.0f,
    151.0f, 150.0f, 149.0f, 148.0f, 147.0f, 146.0f,
    145.0f,
};

const gc_point_t *gc_pred_hist_2 = pred_hist_2;
const gc_point_t *gc_pred_bolus_2 = pred_bolus_2;
const float *gc_pred_device_2 = pred_device_2;

static const gc_point_t pred_hist_3[1] = {{0, 0.0f}};
static const gc_point_t pred_bolus_3[1] = {{0, 0.0f}};
static const gc_point_t pred_series_3[1] = {{0, 0.0f}};

const gc_point_t *gc_pred_hist_3 = pred_hist_3;
const gc_point_t *gc_pred_bolus_3 = pred_bolus_3;
const float *gc_pred_device_3 = NULL;

static const gc_point_t pred_hist_4[6] = {
    {1699995800000LL, 120.0f},
    {1699996100000LL, 120.0f},
    {1699996400000LL, 120.0f},
    {1699996700000LL, 120.0f},
    {1699997000000LL, 120.0f},
    {1699997300000LL, 120.0f},
};
static const gc_point_t pred_bolus_4[1] = {{0, 0.0f}};
static const gc_point_t pred_series_4[1] = {{0, 0.0f}};

const gc_point_t *gc_pred_hist_4 = pred_hist_4;
const gc_point_t *gc_pred_bolus_4 = pred_bolus_4;
const float *gc_pred_device_4 = NULL;

static const gc_point_t pred_hist_5[12] = {
    {1699996700000LL, 118.0f},
    {1699997000000LL, 118.0f},
    {1699997300000LL, 118.0f},
    {1699997600000LL, 118.0f},
    {1699997900000LL, 118.0f},
    {1699998200000LL, 118.0f},
    {1699998500000LL, 118.0f},
    {1699998800000LL, 118.0f},
    {1699999100000LL, 118.0f},
    {1699999400000LL, 118.0f},
    {1699999700000LL, 118.0f},
    {1700000000000LL, 118.0f},
};
static const gc_point_t pred_bolus_5[1] = {
    {1699997900000LL, 2.0f},
};
static const gc_point_t pred_series_5[24] = {
    {1700000300000LL, 115.941431f},
    {1700000600000LL, 113.75466f},
    {1700000900000LL, 111.464423f},
    {1700001200000LL, 109.093008f},
    {1700001500000LL, 106.660454f},
    {1700001800000LL, 104.184728f},
    {1700002100000LL, 101.681897f},
    {1700002400000LL, 99.166284f},
    {1700002700000LL, 96.65061f},
    {1700003000000LL, 94.14613f},
    {1700003300000LL, 91.662761f},
    {1700003600000LL, 89.209191f},
    {1700003900000LL, 86.792989f},
    {1700004200000LL, 84.420706f},
    {1700004500000LL, 82.097961f},
    {1700004800000LL, 79.82953f},
    {1700005100000LL, 77.61942f},
    {1700005400000LL, 75.470946f},
    {1700005700000LL, 73.386792f},
    {1700006000000LL, 71.369076f},
    {1700006300000LL, 69.419403f},
    {1700006600000LL, 67.538919f},
    {1700006900000LL, 65.728361f},
    {1700007200000LL, 63.988095f},
};

const gc_point_t *gc_pred_hist_5 = pred_hist_5;
const gc_point_t *gc_pred_bolus_5 = pred_bolus_5;
const float *gc_pred_device_5 = NULL;

const gc_predict_vector_t gc_predict_vectors[] = {
    {
        .name = "device_curve_fresh",
        .snapshot = {
            .has_sgv = true, .sgv = 140.0f, .sgv_date = 1699999880000LL,
            .history = {{0, 0.0f}}, .history_count = 12,
            .boluses = {{0, 0.0f}}, .bolus_count = 0,
            .has_iob = true, .iob = 1.0f,
            .has_cob = true, .cob = 0.0f,
            .has_status = true, .status_date = 1699999820000LL,
            .device_pred = {.valid = true, .start_ms = 1699999820000LL, .count = 26},
            .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        },
        .expect_valid = true,
        .expect_estimated = false,
        .horizon_valid = {true, true, true, true},
        .horizons = {121.0f, 118.0f, 118.0f, 118.0f},
        .series_count = 24,
        .series = pred_series_0,
    },
    {
        .name = "device_curve_stale_falls_back",
        .snapshot = {
            .has_sgv = true, .sgv = 140.0f, .sgv_date = 1699999880000LL,
            .history = {{0, 0.0f}}, .history_count = 12,
            .boluses = {{0, 0.0f}}, .bolus_count = 0,
            .has_iob = true, .iob = 1.0f,
            .has_cob = true, .cob = 0.0f,
            .has_status = true, .status_date = 1699997600000LL,
            .device_pred = {.valid = false},
            .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        },
        .expect_valid = true,
        .expect_estimated = true,
        .horizon_valid = {true, true, true, true},
        .horizons = {129.079106f, 118.853145f, 110.194413f, 103.353f},
        .series_count = 24,
        .series = pred_series_1,
    },
    {
        .name = "loop_style_curve",
        .snapshot = {
            .has_sgv = true, .sgv = 155.0f, .sgv_date = 1699999940000LL,
            .history = {{0, 0.0f}}, .history_count = 12,
            .boluses = {{0, 0.0f}}, .bolus_count = 0,
            .has_iob = true, .iob = 0.5f,
            .has_cob = true, .cob = 12.0f,
            .has_status = true, .status_date = 1699999940000LL,
            .device_pred = {.valid = true, .start_ms = 1699999940000LL, .count = 25},
            .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        },
        .expect_valid = true,
        .expect_estimated = false,
        .horizon_valid = {true, true, true, true},
        .horizons = {165.0f, 157.0f, 151.0f, 145.0f},
        .series_count = 24,
        .series = pred_series_2,
    },
    {
        .name = "no_reading_at_all",
        .snapshot = {
            .has_sgv = false, .sgv = 0.0f, .sgv_date = 0LL,
            .history = {{0, 0.0f}}, .history_count = 0,
            .boluses = {{0, 0.0f}}, .bolus_count = 0,
            .has_iob = false, .iob = 0.0f,
            .has_cob = false, .cob = 0.0f,
            .has_status = false, .status_date = 0LL,
            .device_pred = {.valid = false},
            .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        },
        .expect_valid = false,
        .expect_estimated = false,
        .horizon_valid = {false, false, false, false},
        .horizons = {0.0f, 0.0f, 0.0f, 0.0f},
        .series_count = 0,
        .series = pred_series_3,
    },
    {
        .name = "reading_too_old_to_forecast",
        .snapshot = {
            .has_sgv = true, .sgv = 120.0f, .sgv_date = 1699997300000LL,
            .history = {{0, 0.0f}}, .history_count = 6,
            .boluses = {{0, 0.0f}}, .bolus_count = 0,
            .has_iob = false, .iob = 0.0f,
            .has_cob = false, .cob = 0.0f,
            .has_status = false, .status_date = 0LL,
            .device_pred = {.valid = false},
            .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        },
        .expect_valid = false,
        .expect_estimated = false,
        .horizon_valid = {false, false, false, false},
        .horizons = {0.0f, 0.0f, 0.0f, 0.0f},
        .series_count = 0,
        .series = pred_series_4,
    },
    {
        .name = "estimate_from_a_fresh_reading",
        .snapshot = {
            .has_sgv = true, .sgv = 118.0f, .sgv_date = 1699999760000LL,
            .history = {{0, 0.0f}}, .history_count = 12,
            .boluses = {{0, 0.0f}}, .bolus_count = 1,
            .has_iob = true, .iob = 1.6f,
            .has_cob = true, .cob = 0.0f,
            .has_status = false, .status_date = 0LL,
            .device_pred = {.valid = false},
            .params = {.has_isf = false, .has_cr = false, .has_dia_hours = false, .has_peak_min = false},
        },
        .expect_valid = true,
        .expect_estimated = true,
        .horizon_valid = {true, true, true, true},
        .horizons = {104.184728f, 89.209191f, 75.470946f, 63.988095f},
        .series_count = 24,
        .series = pred_series_5,
    },
};
const int gc_predict_vector_count = 6;

const gc_version_vector_t gc_version_vectors[] = {
    {"2.0.1", "2.0.0", true},
    {"2.0.0", "2.0.1", false},
    {"2.0.0", "2.0.0", false},
    {"2.0.1", "2.0.1-rc.3", true},
    {"2.0.1-rc.3", "2.0.1", false},
    {"2.0.1-rc.4", "2.0.1-rc.3", true},
    {"2.0.1-rc.3", "2.0.1-rc.4", false},
    {"2.0.0-rc.1", "2.0.0-beta5", true},
    {"2.0.0-beta2", "2.0.0-alpha3", true},
    {"2.0.0-pre1", "2.0.0-alpha9", true},
    {"1.0", "1.0.0", false},
    {"1.0.0", "1.0", false},
    {"1.0.1", "1.0", true},
    {"v2.1.0", "2.0.9", true},
    {"2.1.0", "v2.0.9", true},
    {"3.0.0", "2.99.99", true},
    {"10.0.0", "9.99.99", true},
    {"2.0.10", "2.0.9", true},
    {"banana", "2.0.0", false},
    {"2.0.0", "banana", false},
    {"", "2.0.0", false},
    {"2.0.0-dev", "1.0.0", false},
    {"1.0.0", "2.0.0-dev", false},
    {"2.0.0", "0.0.0", true},
};
const int gc_version_vector_count = 24;

const gc_prerelease_vector_t gc_prerelease_vectors[] = {
    {"2.0.0", false},
    {"2.0.1-rc.3", true},
    {"v2.0.1-rc.3", true},
    {"2.0.0-beta2", true},
    {"2.0.0-alpha1", true},
    {"2.0.0-pre1", true},
    {"1.0", false},
    {"banana", false},
    {"", false},
    {"2.0.0-dev", false},
};
const int gc_prerelease_vector_count = 10;

const gc_point_t *gc_predict_history(int index) {
    switch (index) {
    case 0: return gc_pred_hist_0;
    case 1: return gc_pred_hist_1;
    case 2: return gc_pred_hist_2;
    case 3: return gc_pred_hist_3;
    case 4: return gc_pred_hist_4;
    case 5: return gc_pred_hist_5;
    default: return NULL;
    }
}

const gc_point_t *gc_predict_boluses(int index) {
    switch (index) {
    case 0: return gc_pred_bolus_0;
    case 1: return gc_pred_bolus_1;
    case 2: return gc_pred_bolus_2;
    case 3: return gc_pred_bolus_3;
    case 4: return gc_pred_bolus_4;
    case 5: return gc_pred_bolus_5;
    default: return NULL;
    }
}

const float *gc_predict_device_values(int index) {
    switch (index) {
    case 0: return gc_pred_device_0;
    case 1: return gc_pred_device_1;
    case 2: return gc_pred_device_2;
    case 3: return gc_pred_device_3;
    case 4: return gc_pred_device_4;
    case 5: return gc_pred_device_5;
    default: return NULL;
    }
}
