/*
 * Generated by firmware/tools/gen_contract.py from glucocube/contract.py.
 * Do not edit by hand — edit the Python and regenerate, or CI will fail.
 */

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* ------------------------------------------------- palette -- */

typedef enum {
    GC_C_BG,
    GC_C_BAND,
    GC_C_LINE,
    GC_C_FG,
    GC_C_DIM,
    GC_C_FAINT,
    GC_C_TRACE,
    GC_C_STALE,
    GC_C_IN_RANGE,
    GC_C_HIGH,
    GC_C_LOW,
    GC_C_URGENT,
    GC_C_COUNT,
} gc_color_t;

typedef enum {
    GC_THEME_DARK,
    GC_THEME_LIGHT,
    GC_THEME_COUNT,
} gc_theme_t;

#define GC_DEFAULT_THEME GC_THEME_DARK

/* 0xRRGGBB, exactly as the Pi draws them. */
extern const uint32_t gc_palette[GC_THEME_COUNT][GC_C_COUNT];

/* The same colour packed for a 16-bit RGB565 panel. */
uint16_t gc_color565(gc_theme_t theme, gc_color_t role);
uint32_t gc_color888(gc_theme_t theme, gc_color_t role);
uint16_t gc_rgb_to_565(uint32_t rgb);
const char *gc_theme_name(gc_theme_t theme);
gc_theme_t gc_theme_from_name(const char *name);

/* thresholds */
#define GC_LOW_DEFAULT 70.0
#define GC_HIGH_DEFAULT 180.0
#define GC_URGENT_LOW_DEFAULT 55.0
#define GC_URGENT_HIGH_DEFAULT 250.0
#define GC_STALE_MINUTES_DEFAULT 12.0
#define GC_FRESH_MINUTES 7.0
#define GC_MGDL_PER_MMOL 18.0182

/* forecast */
#define GC_STEP_MS 300000
#define GC_MAX_PREDICTION_AGE_MS 900000
#define GC_MIN_5M_CARBIMPACT 8.0
#define GC_UAM_DECAY_STEPS 12
#define GC_CLAMP_LO 39.0
#define GC_CLAMP_HI 401.0
#define GC_STEP_MIN 5.0
#define GC_DEVIATION_WINDOW_MS 2700000
#define GC_DEVIATION_MIN_GAP_MIN 2.0
#define GC_DEVIATION_MAX_GAP_MIN 12.0
#define GC_IOB_SCALE_MIN 0.25
#define GC_IOB_SCALE_MAX 4.0
#define GC_SYNTHETIC_BOLUS_AGE_MIN 60.0
#define GC_SYNTHETIC_BOLUS_MIN_FRAC 0.05
#define GC_UAM_DEVIATION_THRESHOLD 2.0
#define GC_PEAK_MAX_FRACTION_OF_DIA 0.45
#define GC_ISF_DEFAULT 50.0
#define GC_CR_DEFAULT 10.0
#define GC_DIA_HOURS_DEFAULT 6.0
#define GC_PEAK_MIN_DEFAULT 75.0
#define GC_ISF_MIN 10.0
#define GC_ISF_MAX 400.0
#define GC_CR_MIN 2.0
#define GC_CR_MAX 50.0
#define GC_DIA_HOURS_MIN 3.0
#define GC_DIA_HOURS_MAX 10.0
#define GC_PEAK_MIN_MIN 30.0
#define GC_PEAK_MIN_MAX 120.0

/* chart */
#define GC_CHART_HISTORY_MINUTES 180
#define GC_CHART_FORECAST_MINUTES 120
#define GC_CHART_PAD_BELOW 18.0
#define GC_CHART_PAD_ABOVE 24.0
#define GC_CHART_GAP_SPLIT_MS 900000
#define GC_CONE_BASE_SPREAD 4.0
#define GC_CONE_RATE_DEVICE 0.17
#define GC_CONE_RATE_ESTIMATE 0.26
#define GC_CONE_ALPHA 30
#define GC_NOW_HALO_ALPHA 46

/* interaction */
#define GC_QR_OPEN_SECONDS 120
#define GC_TAP_DEBOUNCE_SECONDS 0.5
#define GC_TAP_FLASH_SECONDS 0.35
#define GC_UPDATE_CHECK_HOURS 6

/* network */
#define GC_HOTSPOT_SSID "GlucoCube-Setup"
#define GC_HOTSPOT_ADDR "10.42.0.1"
#define GC_MDNS_HOSTNAME "glucocube"
#define GC_NET_CHECK_SECONDS 30
#define GC_NET_FAILS_NEEDED 3
#define GC_NET_FIRST_CHECK_DELAY 5
#define GC_NET_SCAN_REFRESH_SECONDS 300
#define GC_CAPTIVE_PROBE_COUNT 12
extern const char *const gc_captive_probe_paths[GC_CAPTIVE_PROBE_COUNT];
#define GC_CAPTIVE_ALWAYS_SERVE_COUNT 4
extern const char *const gc_captive_always_serve[GC_CAPTIVE_ALWAYS_SERVE_COUNT];

/* QR codes */
#define GC_QR_ERROR_CORRECTION "M"
#define GC_QR_BORDER_MODULES 2

#define GC_UNITS_MGDL "mg/dL"
#define GC_REPO "The-Carted-Horse/SugarCube"
#define GC_FORCE_MARKER "[force-update]"

#define GC_HORIZON_COUNT 4
extern const int gc_horizons[GC_HORIZON_COUNT];
#define GC_HORIZON_FAR 120

/* -------------------------------------------------- layout -- */
/* Fractions of the panel's own height (h) or width (w); names
   ending in _PX are pixel floors, not fractions. */

#define GC_L_ARROW_SIZE_H 0.06
#define GC_L_ARROW_Y_CAP 0.16
#define GC_L_BADGE_DOT_GAP_H 0.035
#define GC_L_BADGE_DOT_R_H 0.011
#define GC_L_BADGE_DOT_R_PX 3
#define GC_L_BADGE_PX_H 0.032
#define GC_L_BADGE_TOP_H 0.012
#define GC_L_CHART_AXIS_GAP_H 0.022
#define GC_L_CHART_AXIS_PX_H 0.026
#define GC_L_CHART_BAND_LABEL_INSET 5
#define GC_L_CHART_BAND_LABEL_PX_H 0.15
#define GC_L_CHART_BAND_LABEL_PX_MIN 10
#define GC_L_CHART_BAND_THIN_RATIO 2.4
#define GC_L_CHART_DOT_R_H 0.022
#define GC_L_CHART_DOT_R_PX 1.6
#define GC_L_CHART_HEIGHT_H 0.2
#define GC_L_CHART_NOW_DASH_ON 4
#define GC_L_CHART_NOW_DASH_PERIOD 9
#define GC_L_CHART_NOW_R_H 0.075
#define GC_L_CHART_NOW_R_PX 4
#define GC_L_CHART_TOP_H 0.53
#define GC_L_DELTA_PX_H 0.08
#define GC_L_DELTA_Y_CAP 0.36
#define GC_L_FOOTER_GLYPH_ADVANCE 0.85
#define GC_L_FOOTER_H 0.072
#define GC_L_FOOTER_H_PX 26
#define GC_L_FOOTER_ICON_R_H 0.14
#define GC_L_FOOTER_ICON_R_PX 6
#define GC_L_FOOTER_MARK_PX_MIN 9
#define GC_L_FOOTER_MARK_PX_RATIO 0.92
#define GC_L_FOOTER_MARK_SIZE_RATIO 1.35
#define GC_L_FOOTER_PAD_W 0.028
#define GC_L_FOOTER_PX_H 0.3
#define GC_L_FOOTER_PX_MIN 11
#define GC_L_FOOTER_UPDATE_GAP 2.2
#define GC_L_FORECAST_ETA_GAP_W 0.025
#define GC_L_FORECAST_LABEL_PX_H 0.031
#define GC_L_FORECAST_RULE_GAP_W 0.03
#define GC_L_FORECAST_VALUE_PX_H 0.055
#define GC_L_FORECAST_Y_H 0.48
#define GC_L_HEADER_TOP_H 0.055
#define GC_L_LABEL_TRACKING 0.22
#define GC_L_NAME_PX_H 0.052
#define GC_L_NUM_CAP_RATIO 0.7
#define GC_L_NUM_LEFT_NUDGE 0.05
#define GC_L_NUM_MAX_W_RESERVE_W 0.26
#define GC_L_NUM_PX_H 0.33
#define GC_L_NUM_PX_MIN 12
#define GC_L_NUM_TOP_H 0.125
#define GC_L_PANEL_DIVIDER_INSET_LANDSCAPE 0.05
#define GC_L_PANEL_DIVIDER_INSET_LANDSCAPE_BOTTOM 0.03
#define GC_L_PANEL_DIVIDER_INSET_PORTRAIT 0.03
#define GC_L_PANEL_PAD_W 0.075
#define GC_L_QR_GLYPH_CELL_H 0.5
#define GC_L_QR_GLYPH_CELL_PX 2
#define GC_L_QR_MIN_LEFT_W 0.34
#define GC_L_QR_W_PX 104
#define GC_L_QR_W_RATIO 10
#define GC_L_STATS_LABEL_PX_H 0.028
#define GC_L_STATS_LABEL_Y_H 0.815
#define GC_L_STATS_SUB_GAP_H 0.1
#define GC_L_STATS_SUB_PX_H 0.024
#define GC_L_STATS_UNIT_GAP 0.08
#define GC_L_STATS_UNIT_RATIO 0.5
#define GC_L_STATS_VALUE_GAP_H 0.048
#define GC_L_STATS_VALUE_PX_H 0.082
#define GC_L_TOGGLE_H_PX 44
#define GC_L_TOGGLE_H_RATIO 2
#define GC_L_TOGGLE_W_PX 120
#define GC_L_TOGGLE_W_RATIO 11
#define GC_L_TREND_GAP_W 0.04
#define GC_L_UNIT_PX_H 0.027
#define GC_L_UNIT_Y_CAP 0.8
#define GC_L_URGENT_INSET 6
#define GC_L_URGENT_RADIUS 12
#define GC_L_URGENT_WIDTH 3

typedef struct {
    const char *direction;
    int angle_deg;
    int heads;
} gc_direction_t;

#define GC_DIRECTION_COUNT 7
extern const gc_direction_t gc_directions[GC_DIRECTION_COUNT];
const gc_direction_t *gc_direction_lookup(const char *name);

typedef struct {
    int minutes;
    const char *label;
} gc_tick_t;

#define GC_TICK_COUNT 6
extern const gc_tick_t gc_ticks[GC_TICK_COUNT];

const char *gc_source_label(const char *source_type);

#define GC_QR_GLYPH_ROWS 7
#define GC_QR_GLYPH_COLS 7
extern const char *const gc_qr_glyph[GC_QR_GLYPH_ROWS];

typedef enum {
    GC_CHANNEL_STABLE,
    GC_CHANNEL_BETA,
    GC_CHANNEL_COUNT,
} gc_channel_t;

const char *gc_channel_name(gc_channel_t channel);
const char *gc_channel_label(gc_channel_t channel);
gc_channel_t gc_channel_from_name(const char *name);

