#!/usr/bin/env python3
"""Turn glucocube/contract.py into the C header the firmware compiles against.

The Pi and the ESP32 render the same dashboard from the same numbers. Rather
than typing those numbers out twice, the Python module is the source of truth
and this script writes the C:

    firmware/components/gc_contract/include/gc_contract.h
    firmware/components/gc_contract/gc_contract.c

Run it after editing ``glucocube/contract.py``:

    python3 firmware/tools/gen_contract.py

``tests/test_contract.py`` regenerates into a temporary directory and compares,
so CI fails if the two ever drift apart.
"""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from glucocube import contract  # noqa: E402

HEADER_PATH = "firmware/components/gc_contract/include/gc_contract.h"
SOURCE_PATH = "firmware/components/gc_contract/gc_contract.c"

BANNER = """/*
 * Generated by firmware/tools/gen_contract.py from glucocube/contract.py.
 * Do not edit by hand — edit the Python and regenerate, or CI will fail.
 */
"""


def cfloat(value: float) -> str:
    """A C literal for a Python float.

    Deliberately *not* f-suffixed. The forecast is evaluated in doubles on
    both devices so that the golden vectors match, and 0.17f is not 0.17:
    a single-precision constant folded into that arithmetic is a source of
    drift that no test would obviously explain.
    """
    return repr(float(value))


def cident(name: str) -> str:
    return "GC_" + name.upper()


def rgb_hex(rgb) -> str:
    return "0x%02X%02X%02X" % tuple(int(c) for c in rgb)


def gen_header() -> str:
    out = [BANNER, "#pragma once", "", "#include <stdbool.h>",
           "#include <stddef.h>", "#include <stdint.h>", ""]

    # ---- palette ----
    out += ["/* ------------------------------------------------- palette -- */", ""]
    out.append("typedef enum {")
    for role in contract.PALETTE_ROLES:
        out.append(f"    GC_C_{role.upper()},")
    out.append("    GC_C_COUNT,")
    out.append("} gc_color_t;")
    out.append("")
    out.append("typedef enum {")
    for theme in contract.PALETTES:
        out.append(f"    GC_THEME_{theme.upper()},")
    out.append("    GC_THEME_COUNT,")
    out.append("} gc_theme_t;")
    out.append("")
    out.append(f"#define GC_DEFAULT_THEME GC_THEME_{contract.DEFAULT_THEME.upper()}")
    out.append("")
    out.append("/* 0xRRGGBB, exactly as the Pi draws them. */")
    out.append("extern const uint32_t gc_palette[GC_THEME_COUNT][GC_C_COUNT];")
    out.append("")
    out.append("/* The same colour packed for a 16-bit RGB565 panel. */")
    out.append("uint16_t gc_color565(gc_theme_t theme, gc_color_t role);")
    out.append("uint32_t gc_color888(gc_theme_t theme, gc_color_t role);")
    out.append("uint16_t gc_rgb_to_565(uint32_t rgb);")
    out.append("const char *gc_theme_name(gc_theme_t theme);")
    out.append("gc_theme_t gc_theme_from_name(const char *name);")
    out.append("")

    # ---- scalars ----
    scalars = [
        ("thresholds", [
            ("LOW_DEFAULT", contract.THRESHOLD_DEFAULTS["low"]),
            ("HIGH_DEFAULT", contract.THRESHOLD_DEFAULTS["high"]),
            ("URGENT_LOW_DEFAULT", contract.THRESHOLD_DEFAULTS["urgent_low"]),
            ("URGENT_HIGH_DEFAULT", contract.THRESHOLD_DEFAULTS["urgent_high"]),
            ("STALE_MINUTES_DEFAULT", contract.STALE_MINUTES_DEFAULT),
            ("FRESH_MINUTES", contract.FRESH_MINUTES),
            ("MGDL_PER_MMOL", contract.MGDL_PER_MMOL),
        ]),
        ("forecast", [
            ("STEP_MS", contract.STEP_MS),
            ("MAX_PREDICTION_AGE_MS", contract.MAX_PREDICTION_AGE_MS),
            ("MIN_5M_CARBIMPACT", contract.MIN_5M_CARBIMPACT),
            ("UAM_DECAY_STEPS", contract.UAM_DECAY_STEPS),
            ("CLAMP_LO", contract.CLAMP_LO),
            ("CLAMP_HI", contract.CLAMP_HI),
            ("STEP_MIN", contract.STEP_MIN),
            ("DEVIATION_WINDOW_MS", contract.DEVIATION_WINDOW_MS),
            ("DEVIATION_MIN_GAP_MIN", contract.DEVIATION_MIN_GAP_MIN),
            ("DEVIATION_MAX_GAP_MIN", contract.DEVIATION_MAX_GAP_MIN),
            ("IOB_SCALE_MIN", contract.IOB_SCALE_MIN),
            ("IOB_SCALE_MAX", contract.IOB_SCALE_MAX),
            ("SYNTHETIC_BOLUS_AGE_MIN", contract.SYNTHETIC_BOLUS_AGE_MIN),
            ("SYNTHETIC_BOLUS_MIN_FRAC", contract.SYNTHETIC_BOLUS_MIN_FRAC),
            ("UAM_DEVIATION_THRESHOLD", contract.UAM_DEVIATION_THRESHOLD),
            ("PEAK_MAX_FRACTION_OF_DIA", contract.PEAK_MAX_FRACTION_OF_DIA),
            ("ISF_DEFAULT", contract.THERAPY_DEFAULTS["isf"]),
            ("CR_DEFAULT", contract.THERAPY_DEFAULTS["cr"]),
            ("DIA_HOURS_DEFAULT", contract.THERAPY_DEFAULTS["dia_hours"]),
            ("PEAK_MIN_DEFAULT", contract.THERAPY_DEFAULTS["peak_min"]),
            ("ISF_MIN", contract.THERAPY_RANGES["isf"][0]),
            ("ISF_MAX", contract.THERAPY_RANGES["isf"][1]),
            ("CR_MIN", contract.THERAPY_RANGES["cr"][0]),
            ("CR_MAX", contract.THERAPY_RANGES["cr"][1]),
            ("DIA_HOURS_MIN", contract.THERAPY_RANGES["dia_hours"][0]),
            ("DIA_HOURS_MAX", contract.THERAPY_RANGES["dia_hours"][1]),
            ("PEAK_MIN_MIN", contract.THERAPY_RANGES["peak_min"][0]),
            ("PEAK_MIN_MAX", contract.THERAPY_RANGES["peak_min"][1]),
        ]),
        ("chart", [
            ("CHART_HISTORY_MINUTES", contract.CHART_HISTORY_MINUTES),
            ("CHART_FORECAST_MINUTES", contract.CHART_FORECAST_MINUTES),
            ("CHART_PAD_BELOW", contract.CHART_PAD_BELOW),
            ("CHART_PAD_ABOVE", contract.CHART_PAD_ABOVE),
            ("CHART_GAP_SPLIT_MS", contract.CHART_GAP_SPLIT_MS),
            ("CONE_BASE_SPREAD", contract.CONE_BASE_SPREAD),
            ("CONE_RATE_DEVICE", contract.CONE_RATE_DEVICE),
            ("CONE_RATE_ESTIMATE", contract.CONE_RATE_ESTIMATE),
            ("CONE_ALPHA", contract.CONE_ALPHA),
            ("NOW_HALO_ALPHA", contract.NOW_HALO_ALPHA),
        ]),
        ("interaction", [
            ("QR_OPEN_SECONDS", contract.QR_OPEN_SECONDS),
            ("TAP_DEBOUNCE_SECONDS", contract.TAP_DEBOUNCE_SECONDS),
            ("TAP_FLASH_SECONDS", contract.TAP_FLASH_SECONDS),
            ("UPDATE_CHECK_HOURS", contract.UPDATE_CHECK_HOURS),
        ]),
    ]
    for title, items in scalars:
        out.append(f"/* {title} */")
        for name, value in items:
            literal = str(value) if isinstance(value, int) else cfloat(value)
            out.append(f"#define {cident(name)} {literal}")
        out.append("")

    out.append("/* network */")
    out.append(f'#define GC_HOTSPOT_SSID "{contract.HOTSPOT_SSID}"')
    out.append(f'#define GC_HOTSPOT_ADDR "{contract.HOTSPOT_ADDR}"')
    out.append(f'#define GC_MDNS_HOSTNAME "{contract.MDNS_HOSTNAME}"')
    for name in ("NET_CHECK_SECONDS", "NET_FAILS_NEEDED",
                 "NET_FIRST_CHECK_DELAY", "NET_SCAN_REFRESH_SECONDS"):
        out.append(f"#define {cident(name)} {getattr(contract, name)}")
    out.append(f"#define GC_CAPTIVE_PROBE_COUNT {len(contract.CAPTIVE_PROBE_PATHS)}")
    out.append("extern const char *const gc_captive_probe_paths[GC_CAPTIVE_PROBE_COUNT];")
    out.append(f"#define GC_CAPTIVE_ALWAYS_SERVE_COUNT {len(contract.CAPTIVE_ALWAYS_SERVE)}")
    out.append("extern const char *const gc_captive_always_serve[GC_CAPTIVE_ALWAYS_SERVE_COUNT];")
    out.append("")
    out.append("/* QR codes */")
    out.append(f'#define GC_QR_ERROR_CORRECTION "{contract.QR_ERROR_CORRECTION}"')
    out.append(f"#define GC_QR_BORDER_MODULES {contract.QR_BORDER_MODULES}")
    out.append("")
    out.append(f'#define GC_UNITS_MGDL "{contract.UNITS_MGDL}"')
    out.append(f'#define GC_REPO "{contract.REPO}"')
    out.append(f'#define GC_FORCE_MARKER "{contract.FORCE_MARKER}"')
    out.append("")

    # ---- horizons ----
    out.append(f"#define GC_HORIZON_COUNT {len(contract.HORIZONS)}")
    out.append("extern const int gc_horizons[GC_HORIZON_COUNT];")
    out.append(f"#define GC_HORIZON_FAR {contract.HORIZONS[-1]}")
    out.append("")

    # ---- layout ----
    out += ["/* -------------------------------------------------- layout -- */",
            "/* Fractions of the panel's own height (h) or width (w); names",
            "   ending in _PX are pixel floors, not fractions. */", ""]
    for name in sorted(contract.LAYOUT):
        value = contract.LAYOUT[name]
        literal = str(value) if isinstance(value, int) else cfloat(value)
        out.append(f"#define {cident('L_' + name)} {literal}")
    out.append("")

    # ---- trend arrows ----
    out.append("typedef struct {")
    out.append("    const char *direction;")
    out.append("    int angle_deg;")
    out.append("    int heads;")
    out.append("} gc_direction_t;")
    out.append("")
    out.append(f"#define GC_DIRECTION_COUNT {len(contract.DIRECTION_ANGLES)}")
    out.append("extern const gc_direction_t gc_directions[GC_DIRECTION_COUNT];")
    out.append("const gc_direction_t *gc_direction_lookup(const char *name);")
    out.append("")

    # ---- chart ticks ----
    out.append("typedef struct {")
    out.append("    int minutes;")
    out.append("    const char *label;")
    out.append("} gc_tick_t;")
    out.append("")
    out.append(f"#define GC_TICK_COUNT {len(contract.CHART_TICKS)}")
    out.append("extern const gc_tick_t gc_ticks[GC_TICK_COUNT];")
    out.append("")

    # ---- source badges ----
    out.append("const char *gc_source_label(const char *source_type);")
    out.append("")

    # ---- QR glyph ----
    out.append(f"#define GC_QR_GLYPH_ROWS {len(contract.QR_GLYPH)}")
    out.append(f"#define GC_QR_GLYPH_COLS {len(contract.QR_GLYPH[0])}")
    out.append("extern const char *const gc_qr_glyph[GC_QR_GLYPH_ROWS];")
    out.append("")

    # ---- channels ----
    out.append("typedef enum {")
    for channel in contract.UPDATE_CHANNELS:
        out.append(f"    GC_CHANNEL_{channel.upper()},")
    out.append("    GC_CHANNEL_COUNT,")
    out.append("} gc_channel_t;")
    out.append("")
    out.append("const char *gc_channel_name(gc_channel_t channel);")
    out.append("const char *gc_channel_label(gc_channel_t channel);")
    out.append("gc_channel_t gc_channel_from_name(const char *name);")
    out.append("")
    return "\n".join(out) + "\n"


def gen_source() -> str:
    out = [BANNER, '#include "gc_contract.h"', "", "#include <string.h>", ""]

    out.append("const uint32_t gc_palette[GC_THEME_COUNT][GC_C_COUNT] = {")
    for theme, colors in contract.PALETTES.items():
        out.append(f"    [GC_THEME_{theme.upper()}] = {{")
        for role in contract.PALETTE_ROLES:
            out.append(f"        [GC_C_{role.upper()}] = {rgb_hex(colors[role])},")
        out.append("    },")
    out.append("};")
    out.append("")

    out.append("static const char *const theme_names[GC_THEME_COUNT] = {")
    for theme in contract.PALETTES:
        out.append(f'    [GC_THEME_{theme.upper()}] = "{theme}",')
    out.append("};")
    out.append("")

    out.append("""uint16_t gc_rgb_to_565(uint32_t rgb)
{
    uint32_t r = (rgb >> 16) & 0xFF, g = (rgb >> 8) & 0xFF, b = rgb & 0xFF;
    return (uint16_t)(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3));
}

uint32_t gc_color888(gc_theme_t theme, gc_color_t role)
{
    if (theme >= GC_THEME_COUNT || role >= GC_C_COUNT) {
        return 0;
    }
    return gc_palette[theme][role];
}

uint16_t gc_color565(gc_theme_t theme, gc_color_t role)
{
    return gc_rgb_to_565(gc_color888(theme, role));
}

const char *gc_theme_name(gc_theme_t theme)
{
    return theme < GC_THEME_COUNT ? theme_names[theme] : theme_names[GC_DEFAULT_THEME];
}

gc_theme_t gc_theme_from_name(const char *name)
{
    for (int i = 0; name && i < GC_THEME_COUNT; i++) {
        if (strcmp(name, theme_names[i]) == 0) {
            return (gc_theme_t)i;
        }
    }
    return GC_DEFAULT_THEME;
}
""")

    out.append("const int gc_horizons[GC_HORIZON_COUNT] = {"
               + ", ".join(str(h) for h in contract.HORIZONS) + "};")
    out.append("")

    out.append("const gc_direction_t gc_directions[GC_DIRECTION_COUNT] = {")
    for name, (angle, heads) in contract.DIRECTION_ANGLES.items():
        out.append(f'    {{"{name}", {angle}, {heads}}},')
    out.append("};")
    out.append("")
    out.append("""const gc_direction_t *gc_direction_lookup(const char *name)
{
    for (int i = 0; name && i < GC_DIRECTION_COUNT; i++) {
        if (strcmp(name, gc_directions[i].direction) == 0) {
            return &gc_directions[i];
        }
    }
    return NULL;
}
""")

    out.append("const gc_tick_t gc_ticks[GC_TICK_COUNT] = {")
    for minutes, label in contract.CHART_TICKS:
        out.append(f'    {{{minutes}, "{label}"}},')
    out.append("};")
    out.append("")

    out.append("static const struct { const char *type; const char *label; }"
               " source_labels[] = {")
    for stype, label in contract.SOURCE_LABELS.items():
        out.append(f'    {{"{stype}", "{label}"}},')
    out.append("};")
    out.append("")
    out.append(f"""const char *gc_source_label(const char *source_type)
{{
    size_t n = sizeof(source_labels) / sizeof(source_labels[0]);
    for (size_t i = 0; source_type && i < n; i++) {{
        if (strcmp(source_type, source_labels[i].type) == 0) {{
            return source_labels[i].label;
        }}
    }}
    return "{contract.SOURCE_LABEL_DEFAULT}";
}}
""")

    out.append("const char *const gc_captive_probe_paths[GC_CAPTIVE_PROBE_COUNT] = {")
    for path in contract.CAPTIVE_PROBE_PATHS:
        out.append(f'    "{path}",')
    out.append("};")
    out.append("")
    out.append("const char *const gc_captive_always_serve"
               "[GC_CAPTIVE_ALWAYS_SERVE_COUNT] = {")
    for path in contract.CAPTIVE_ALWAYS_SERVE:
        out.append(f'    "{path}",')
    out.append("};")
    out.append("")
    out.append("const char *const gc_qr_glyph[GC_QR_GLYPH_ROWS] = {")
    for row in contract.QR_GLYPH:
        out.append(f'    "{row}",')
    out.append("};")
    out.append("")

    out.append("static const char *const channel_names[GC_CHANNEL_COUNT] = {")
    for channel in contract.UPDATE_CHANNELS:
        out.append(f'    [GC_CHANNEL_{channel.upper()}] = "{channel}",')
    out.append("};")
    out.append("")
    out.append("static const char *const channel_labels[GC_CHANNEL_COUNT] = {")
    for channel in contract.UPDATE_CHANNELS:
        label = contract.CHANNEL_LABELS[channel]
        out.append(f'    [GC_CHANNEL_{channel.upper()}] = "{label}",')
    out.append("};")
    out.append("")
    out.append(f"""const char *gc_channel_name(gc_channel_t channel)
{{
    return channel < GC_CHANNEL_COUNT ? channel_names[channel]
                                      : channel_names[GC_CHANNEL_{contract.UPDATE_CHANNELS[0].upper()}];
}}

const char *gc_channel_label(gc_channel_t channel)
{{
    return channel < GC_CHANNEL_COUNT ? channel_labels[channel]
                                      : channel_labels[GC_CHANNEL_{contract.UPDATE_CHANNELS[0].upper()}];
}}

gc_channel_t gc_channel_from_name(const char *name)
{{
    for (int i = 0; name && i < GC_CHANNEL_COUNT; i++) {{
        if (strcmp(name, channel_names[i]) == 0) {{
            return (gc_channel_t)i;
        }}
    }}
    return GC_CHANNEL_{contract.UPDATE_CHANNELS[0].upper()};
}}
""")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(ROOT),
                        help="tree to write into (default: the repository)")
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the tree is out of date")
    args = parser.parse_args()

    root = Path(args.out)
    files = {root / HEADER_PATH: gen_header(), root / SOURCE_PATH: gen_source()}
    stale = []
    for path, content in files.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"wrote {path}")
    if stale:
        print("out of date: " + ", ".join(str(p) for p in stale), file=sys.stderr)
        print("run: python3 firmware/tools/gen_contract.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
